apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}-secrets
type: Opaque
stringData:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
