apisix:
  node_listen: 9080
  enable_ipv6: false
  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092

deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    admin_key:
      - name: "admin"
        key: remittance-admin-key
        role: admin
    enable_admin_cors: true
    admin_listen:
      ip: 0.0.0.0
      port: 9091
    https_admin: false

etcd:
  host:
    - "http://etcd:2379"
  prefix: "/apisix"
  timeout: 30

plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091

plugins:
  - real-ip
  - ai
  - client-control
  - proxy-control
  - request-id
  - zipkin
  - ext-plugin-pre-req
  - fault-injection
  - mocking
  - serverless-pre-function
  - cors
  - ip-restriction
  - ua-restriction
  - referer-restriction
  - csrf
  - uri-blocker
  - request-validation
  - openid-connect
  - cas-auth
  - authz-casbin
  - authz-casdoor
  - wolf-rbac
  - ldap-auth
  - hmac-auth
  - basic-auth
  - jwt-auth
  - key-auth
  - consumer-restriction
  - authz-keycloak
  - opa
  - forward-auth
  - multi-auth
  - api-breaker
  - limit-req
  - limit-count
  - limit-conn
  - degraphql
  - proxy-cache
  - body-transformer
  - proxy-mirror
  - proxy-rewrite
  - workflow
  - redirect
  - response-rewrite
  - serverless-post-function
  - ext-plugin-post-req
  - file-logger
  - loggly
  - http-logger
  - splunk-hec-logging
  - skywalking-logger
  - google-cloud-logging
  - sls-logger
  - tcp-logger
  - kafka-logger
  - rocketmq-logger
  - syslog
  - udp-logger
  - clickhouse-logger
  - tencent-cloud-cls
  - opensearch-logger
  - openfunction
  - prometheus
  - node-status
  - datadog
  - echo
  - server-info
  - batch-requests
  - opentelemetry
  - inspect
  - public-api

stream_plugins:
  - ip-restriction
  - limit-conn
  - mqtt-proxy
  - syslog

wasm:
  plugins:
    - name: "wasm_log"
      priority: 7999
      file: "/usr/local/apisix/wasm/wasm_log.wasm"

