{{- if .Values.backend.fastapi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "remittance-platform.fullname" . }}-fastapi
  labels:
    {{- include "remittance-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: fastapi-backend
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "remittance-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: fastapi-backend
{{- end }}
