apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: default # Change this to the namespace where your services are deployed
spec:
  mtls:
    mode: STRICT
