from pydantic import BaseModel, Field
from datetime import datetime
from typing import Optional
from models import TransactionStatus, TransactionType

# --- Base Schemas ---

class UPITransactionBase(BaseModel):
    """Base schema for UPI Transaction, containing common fields."""
    reference_id: str = Field(..., description="Internal reference ID (e.g., Merchant Order ID).")
    vpa: str = Field(..., description="Virtual Payment Address (VPA) of the counterparty.")
    amount: float = Field(..., gt=0, description="Transaction amount, must be greater than 0.")
    currency: str = Field("INR", description="Currency code (default: INR).")
    transaction_type: TransactionType = Field(..., description="Type of transaction (PAY or COLLECT).")

# --- Input Schemas ---

class UPITransactionCreate(UPITransactionBase):
    """Schema for creating a new UPI Transaction request."""
    # transaction_id will be generated by the service layer
    pass

class UPITransactionUpdate(BaseModel):
    """Schema for updating an existing UPI Transaction (e.g., status update from a webhook)."""
    transaction_id: str = Field(..., description="External UPI/PSP Transaction ID.")
    status: TransactionStatus = Field(..., description="New status of the transaction.")
    status_message: Optional[str] = Field(None, description="Detailed message about the status change.")
    bank_ref_no: Optional[str] = Field(None, description="Bank reference number (RRN).")

# --- Output Schemas ---

class UPITransactionRead(UPITransactionBase):
    """Schema for reading a UPI Transaction response."""
    id: int
    transaction_id: str
    status: TransactionStatus
    status_message: Optional[str]
    bank_ref_no: Optional[str]
    merchant_code: Optional[str]
    created_at: datetime
    updated_at: datetime

    class Config:
        orm_mode = True
        use_enum_values = True

class UPITransactionList(BaseModel):
    """Schema for listing multiple UPI Transactions."""
    transactions: list[UPITransactionRead]
    total: int

# --- Error Schema ---

class ErrorResponse(BaseModel):
    """Standard error response schema."""
    detail: str
    code: Optional[str] = None
    
    class Config:
        schema_extra = {
            "example": {
                "detail": "Transaction with ID 123 not found.",
                "code": "NOT_FOUND"
            }
        }