apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: remittance-platform
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: "localhost:9092,localhost:9093,localhost:9094"
  - name: consumerGroup
    value: "dapr-remittance-platform"
  - name: clientID
    value: "dapr-client"
  - name: authType
    value: "none"
  - name: maxMessageBytes
    value: "1024000"
  - name: consumeRetryInterval
    value: "200ms"
  - name: version
    value: "2.8.0"
  - name: initialOffset
    value: "newest"
scopes:
- payment-service
- fraud-detection
- user-service
- notification-service

