apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kubernetes-secrets
  namespace: remittance-platform
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
  - name: defaultNamespace
    value: "remittance-platform"
scopes:
- payment-service
- user-service
- fraud-detection
- api-gateway

