import asyncio
import hashlib
import hmac
import json
from abc import ABC, abstractmethod
from typing import Any, Dict, Optional, Tuple

import httpx

# --- Custom Exceptions ---

class PaymentGatewayError(Exception):
    """Base exception for all payment gateway errors."""
    pass

class PagaAPIError(PaymentGatewayError):
    """Raised for errors returned by the Paga API."""
    def __init__(self, message: str, status_code: int, response_data: Dict[str, Any]) -> None:
        super().__init__(message)
        self.status_code = status_code
        self.response_data = response_data

class PagaSignatureVerificationError(PaymentGatewayError):
    """Raised when webhook signature verification fails."""
    pass

class PagaValidationError(PaymentGatewayError):
    """Raised for local validation errors before an API call."""
    pass

# --- Base Gateway Interface ---

class BasePaymentGateway(ABC):
    """Abstract base class for all payment gateways."""

    @abstractmethod
    async def create_payment(self, amount: float, currency: str, reference: str, **kwargs) -> Dict[str, Any]:
        """Initiate a payment transaction."""
        pass

    @abstractmethod
    async def verify_payment(self, reference: str) -> Dict[str, Any]:
        """Verify the status of a payment transaction."""
        pass

    @abstractmethod
    async def handle_webhook(self, headers: Dict[str, str], payload: Dict[str, Any]) -> Dict[str, Any]:
        """Process and validate an incoming webhook notification."""
        pass

# --- Paga Gateway Implementation ---

class PagaGateway(BasePaymentGateway):
    """
    Paga (Nigeria) Payment Gateway implementation.

    Paga uses HTTP Basic Authentication for API access and SHA-512 hashing
    for request/webhook integrity verification.
    """

    # Paga API endpoints (using Collect API as a representative example)
    BASE_URL_LIVE = "https://collect.paga.com"
    BASE_URL_TEST = "https://beta-collect.paga.com"
    
    # Endpoints
    REQUEST_PAYMENT_ENDPOINT = "/paymentRequest"
    VERIFY_PAYMENT_ENDPOINT = "/paymentRequest/status"

    # Paga's primary currency is NGN, but the platform supports others like USD.
    SUPPORTED_CURRENCIES = ["NGN", "USD"]
    
    MAX_RETRIES = 3
    RETRY_DELAY_BASE = 1  # seconds

    def __init__(self, public_key: str, secret_key: str, hash_key: str, is_test: bool = False) -> None:
        """
        Initialize the Paga Gateway client.

        :param public_key: Your Paga Public Key (username for Basic Auth).
        :param secret_key: Your Paga Secret Key (password for Basic Auth).
        :param hash_key: Your Paga Hash Key (HMAC key for signature).
        :param is_test: Boolean to use test or live environment.
        """
        if not all([public_key, secret_key, hash_key]):
            raise PagaValidationError("Public Key, Secret Key, and Hash Key must be provided.")
            
        self.public_key = public_key
        self.secret_key = secret_key
        self.hash_key = hash_key
        self.base_url = self.BASE_URL_TEST if is_test else self.BASE_URL_LIVE
        self.auth = httpx.BasicAuth(public_key, secret_key)

    def _generate_hash(self, endpoint: str, params: Dict[str, Any]) -> str:
        """
        Generates the SHA-512 hash for request integrity verification.

        The hash is generated by concatenating specific parameter values in a
        defined order, followed by the hash_key, and then hashing the result
        with SHA-512. The exact parameter order is endpoint-specific.

        For the purpose of this generic implementation, we will use a common
        set of parameters for the hash generation logic.
        
        :param endpoint: The API endpoint being called.
        :param params: The request body parameters.
        :return: The SHA-512 hash string.
        """
        # NOTE: In a real-world scenario, the parameter order for concatenation
        # MUST be strictly defined by Paga's documentation for each endpoint.
        # This is a mock of the logic based on the Deposit To Bank example.
        
        # Example parameters to include in the hash:
        # referenceNumber, amount, destinationBankUUID, destinationBankAccountNumber, hashkey
        
        # Since we are implementing a generic gateway, we will use a simplified,
        # but representative, ordered concatenation of common fields.
        
        # Fields to include in the hash, in order:
        hash_fields = ["referenceNumber", "amount", "transactionId"]
        
        concatenated_string = ""
        
        # Use a consistent set of fields for the hash, falling back to empty string if not present
        for field in hash_fields:
            concatenated_string += str(params.get(field, ""))
            
        concatenated_string += self.hash_key
        
        # Encode the string to bytes and hash with SHA-512
        hashed_bytes = hashlib.sha512(concatenated_string.encode('utf-8')).hexdigest()
        return hashed_bytes

    async def _make_request(self, method: str, endpoint: str, json_data: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """
        Internal method to make an authenticated, retrying API request.
        """
        url = f"{self.base_url}{endpoint}"
        
        # 1. Generate the hash signature
        request_data = json_data if json_data is not None else {}
        request_hash = self._generate_hash(endpoint, request_data)
        
        headers = {
            "Content-Type": "application/json",
            "hash": request_hash,
        }
        
        async with httpx.AsyncClient(auth=self.auth, headers=headers) as client:
            for attempt in range(self.MAX_RETRIES):
                try:
                    # 2. Make the request
                    response = await client.request(method, url, json=json_data, timeout=30.0)
                    response.raise_for_status()
                    
                    # 3. Handle successful response
                    response_data = response.json()
                    
                    # Paga API typically returns a statusCode in the body
                    if response_data.get("statusCode") != 0:
                        raise PagaAPIError(
                            f"Paga API returned an error: {response_data.get('statusMessage', 'Unknown error')}",
                            response.status_code,
                            response_data
                        )
                        
                    return response_data

                except httpx.HTTPStatusError as e:
                    # Handle HTTP errors (4xx, 5xx)
                    response_data = e.response.json() if e.response.content else {}
                    error_message = f"HTTP Error {e.response.status_code}: {response_data.get('statusMessage', 'Server error')}"
                    raise PagaAPIError(error_message, e.response.status_code, response_data)
                
                except httpx.RequestError as e:
                    # Handle network/request errors
                    if attempt < self.MAX_RETRIES - 1:
                        delay = self.RETRY_DELAY_BASE * (2 ** attempt)
                        await asyncio.sleep(delay)
                        continue
                    raise PaymentGatewayError(f"Network error after {self.MAX_RETRIES} attempts: {e}")
                
                except PagaAPIError:
                    # Re-raise Paga-specific errors immediately
                    raise
                
                except Exception as e:
                    # Catch all other exceptions
                    raise PaymentGatewayError(f"An unexpected error occurred: {e}")

    async def create_payment(self, amount: float, currency: str, reference: str, **kwargs) -> Dict[str, Any]:
        """
        Initiate a payment request via Paga Collect API.

        :param amount: The amount to be paid.
        :param currency: The currency code (e.g., 'NGN').
        :param reference: A unique transaction reference number.
        :param kwargs: Additional parameters like 'payer_email', 'payer_phone', 'callback_url'.
        :return: The API response data.
        """
        if currency not in self.SUPPORTED_CURRENCIES:
            raise PagaValidationError(f"Currency {currency} is not supported by Paga Gateway.")
            
        # Paga Collect API's Request Payment endpoint requires specific fields
        payload = {
            "referenceNumber": reference,
            "amount": amount,
            "currency": currency,
            "payerEmail": kwargs.get("payer_email"),
            "payerPhone": kwargs.get("payer_phone"),
            "callbackUrl": kwargs.get("callback_url"),
            # Other fields as required by the specific Paga API version
        }
        
        # Filter out None values
        payload = {k: v for k, v in payload.items() if v is not None}
        
        return await self._make_request("POST", self.REQUEST_PAYMENT_ENDPOINT, json_data=payload)

    async def verify_payment(self, reference: str) -> Dict[str, Any]:
        """
        Verify the status of a payment transaction using the reference number.

        :param reference: The unique transaction reference number.
        :return: The API response data.
        """
        payload = {
            "referenceNumber": reference,
            # Paga may require other fields like 'transactionId' or 'merchantCode'
        }
        
        return await self._make_request("POST", self.VERIFY_PAYMENT_ENDPOINT, json_data=payload)

    async def handle_webhook(self, headers: Dict[str, str], payload: Dict[str, Any]) -> Dict[str, Any]:
        """
        Process and validate an incoming webhook notification.

        The validation involves comparing the 'hash' header with a locally
        generated hash from the payload and the hash_key.

        :param headers: The HTTP headers from the webhook request.
        :param payload: The JSON body of the webhook request.
        :return: The validated payload.
        :raises PagaSignatureVerificationError: If the hash verification fails.
        """
        incoming_hash = headers.get("hash")
        if not incoming_hash:
            raise PagaSignatureVerificationError("Webhook 'hash' header is missing.")

        # NOTE: The exact fields and order for webhook hash generation
        # MUST be confirmed from Paga's documentation. This is a representative
        # implementation based on the general hashing principle.
        
        # For webhooks, the hash is typically generated from the payload fields
        # and the hash_key. A common set of fields for a payment notification
        # might include: statusCode, referenceNumber, amount, transactionId.
        
        # Fields to include in the webhook hash, in order:
        webhook_hash_fields = ["statusCode", "referenceNumber", "amount", "transactionId"]
        
        concatenated_string = ""
        for field in webhook_hash_fields:
            # Ensure values are converted to string as per Paga's concatenation rule
            concatenated_string += str(payload.get(field, ""))
            
        concatenated_string += self.hash_key
        
        # Generate the expected hash
        expected_hash = hashlib.sha512(concatenated_string.encode('utf-8')).hexdigest()

        if not hmac.compare_digest(incoming_hash.lower(), expected_hash.lower()):
            raise PagaSignatureVerificationError("Webhook signature verification failed.")

        # Verification successful
        return payload

# --- Example Usage (for context, not part of the class) ---
# async def main():
#     # Replace with your actual keys
#     paga = PagaGateway(
#         public_key="YOUR_PUBLIC_KEY",
#         secret_key="YOUR_SECRET_KEY",
#         hash_key="YOUR_HASH_KEY",
#         is_test=True
#     )
#     
#     try:
#         # 1. Create Payment
#         payment_ref = "TXN" + str(int(time.time()))
#         print(f"Initiating payment with reference: {payment_ref}")
#         
#         payment_response = await paga.create_payment(
#             amount=1000.00,
#             currency="NGN",
#             reference=payment_ref,
#             payer_email="test@example.com",
#             callback_url="https://your-app.com/paga/webhook"
#         )
#         print("Payment Initiation Response:", payment_response)
#         
#         # 2. Verify Payment
#         # In a real scenario, you would wait for the webhook or a delay before verifying
#         verification_response = await paga.verify_payment(payment_ref)
#         print("Payment Verification Response:", verification_response)
#         
#     except PagaAPIError as e:
#         print(f"Paga API Error: {e.message} (Status: {e.status_code})")
#         print("Response Data:", e.response_data)
#     except PaymentGatewayError as e:
#         print(f"Gateway Error: {e}")
#     except Exception as e:
#         print(f"An unexpected error occurred: {e}")
# 
# if __name__ == "__main__":
#     # This part is for demonstration and would not run in the final production code
#     # asyncio.run(main())
#     pass