CREATE INDEX "auditLogs_userId_idx" ON "auditLogs" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "auditLogs_createdAt_idx" ON "auditLogs" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "beneficiaries_userId_idx" ON "beneficiaries" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "cards_userId_idx" ON "cards" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "cards_userId_status_idx" ON "cards" USING btree ("userId","status");--> statement-breakpoint
CREATE INDEX "cbdcWallets_userId_idx" ON "cbdc_wallets" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "cbdcWallets_userId_currency_idx" ON "cbdc_wallets" USING btree ("user_id","currency");--> statement-breakpoint
CREATE INDEX "idempotencyKeys_userId_idx" ON "idempotency_keys" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idempotencyKeys_expiresAt_idx" ON "idempotency_keys" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "kycDocuments_userId_idx" ON "kycDocuments" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "kycDocuments_userId_status_idx" ON "kycDocuments" USING btree ("userId","status");--> statement-breakpoint
CREATE INDEX "notifications_userId_idx" ON "notifications" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "notifications_userId_isRead_idx" ON "notifications" USING btree ("userId","isRead");--> statement-breakpoint
CREATE INDEX "savingsGoals_userId_idx" ON "savingsGoals" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "savingsGoals_userId_status_idx" ON "savingsGoals" USING btree ("userId","status");--> statement-breakpoint
CREATE INDEX "transactions_userId_idx" ON "transactions" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "transactions_userId_createdAt_idx" ON "transactions" USING btree ("userId","createdAt");--> statement-breakpoint
CREATE INDEX "transactions_userId_status_idx" ON "transactions" USING btree ("userId","status");--> statement-breakpoint
CREATE INDEX "transactions_reference_idx" ON "transactions" USING btree ("reference");--> statement-breakpoint
CREATE INDEX "transactions_idempotencyKey_idx" ON "transactions" USING btree ("idempotency_key");--> statement-breakpoint
CREATE INDEX "wallets_userId_idx" ON "wallets" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "wallets_userId_currency_idx" ON "wallets" USING btree ("userId","currency");