-- Wave 10 (SPEC-wave10): Melio-feature tables. ADDITIVE ONLY — no existing
-- table or enum modified. Matches drizzle/schema.ts Wave-10 appendix.

CREATE TABLE IF NOT EXISTS vendors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(id),
  owner_user_id integer NOT NULL,
  legal_name varchar(255) NOT NULL,
  display_name varchar(255),
  country varchar(2) NOT NULL,
  currency varchar(3) NOT NULL,
  payout_method jsonb NOT NULL DEFAULT '{}',
  kyb_status varchar(32) NOT NULL DEFAULT 'unverified',
  tin varchar(64),
  wht_rate numeric(5,4),
  tax_doc_status varchar(32) NOT NULL DEFAULT 'none',
  metadata jsonb NOT NULL DEFAULT '{}',
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS vendors_tenant_idx ON vendors (tenant_id, kyb_status);

CREATE TABLE IF NOT EXISTS vendor_bills (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(id),
  vendor_id bigint NOT NULL REFERENCES vendors(id),
  bill_number varchar(128),
  description text,
  amount numeric(18,4) NOT NULL,
  currency varchar(3) NOT NULL,
  due_date timestamp,
  status varchar(32) NOT NULL DEFAULT 'captured',
  source varchar(16) NOT NULL DEFAULT 'manual',
  ocr_confidence numeric(5,4),
  approval_request_id bigint,
  scheduled_at timestamp,
  paid_at timestamp,
  payment_rail varchar(32),
  payment_ref varchar(255),
  speed_tier varchar(16) NOT NULL DEFAULT 'standard',
  idempotency_key varchar(128),
  failure_reason text,
  metadata jsonb NOT NULL DEFAULT '{}',
  created_by integer NOT NULL,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS vendor_bills_idem_uidx ON vendor_bills (idempotency_key);
CREATE INDEX IF NOT EXISTS vendor_bills_tenant_status_idx ON vendor_bills (tenant_id, status);
CREATE INDEX IF NOT EXISTS vendor_bills_vendor_idx ON vendor_bills (vendor_id, status);

CREATE TABLE IF NOT EXISTS bill_documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_id bigint NOT NULL REFERENCES vendor_bills(id),
  storage_key varchar(512) NOT NULL,
  mime varchar(64) NOT NULL,
  ocr_raw jsonb,
  uploaded_by integer NOT NULL,
  created_at timestamp NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS bill_documents_bill_idx ON bill_documents (bill_id);

CREATE TABLE IF NOT EXISTS approval_policies (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(id),
  name varchar(128) NOT NULL,
  scope varchar(32) NOT NULL DEFAULT 'vendor_bill',
  min_amount numeric(18,4) NOT NULL DEFAULT 0,
  currency varchar(3),
  required_approvals integer NOT NULL DEFAULT 1,
  approver_user_ids jsonb NOT NULL DEFAULT '[]',
  approver_roles jsonb NOT NULL DEFAULT '[]',
  allow_self_approval boolean NOT NULL DEFAULT false,
  active boolean NOT NULL DEFAULT true,
  created_by integer NOT NULL,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS approval_policies_tenant_scope_idx ON approval_policies (tenant_id, scope, active);

CREATE TABLE IF NOT EXISTS approval_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(id),
  policy_id bigint NOT NULL REFERENCES approval_policies(id),
  entity_type varchar(32) NOT NULL,
  entity_id varchar(64) NOT NULL,
  amount numeric(18,4) NOT NULL,
  currency varchar(3) NOT NULL,
  status varchar(16) NOT NULL DEFAULT 'pending',
  steps_completed integer NOT NULL DEFAULT 0,
  steps_required integer NOT NULL,
  created_by integer NOT NULL,
  decided_by integer,
  decided_at timestamp,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS approval_requests_entity_idx ON approval_requests (entity_type, entity_id, status);
CREATE INDEX IF NOT EXISTS approval_requests_tenant_idx ON approval_requests (tenant_id, status);

CREATE TABLE IF NOT EXISTS approval_steps (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id bigint NOT NULL REFERENCES approval_requests(id),
  step integer NOT NULL,
  approver_user_id integer NOT NULL,
  status varchar(16) NOT NULL DEFAULT 'pending',
  decided_at timestamp,
  comment text
);
CREATE UNIQUE INDEX IF NOT EXISTS approval_steps_request_step_uidx ON approval_steps (request_id, step);
CREATE INDEX IF NOT EXISTS approval_steps_approver_idx ON approval_steps (approver_user_id, status);

CREATE TABLE IF NOT EXISTS invoices_v2 (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(id),
  customer_name varchar(255) NOT NULL,
  customer_email varchar(255),
  invoice_number varchar(64) NOT NULL,
  currency varchar(3) NOT NULL,
  subtotal numeric(18,4) NOT NULL,
  tax_amount numeric(18,4) NOT NULL DEFAULT 0,
  total numeric(18,4) NOT NULL,
  amount_paid numeric(18,4) NOT NULL DEFAULT 0,
  due_date timestamp,
  status varchar(24) NOT NULL DEFAULT 'draft',
  payment_link_token_hash varchar(64),
  fee_shifting boolean NOT NULL DEFAULT false,
  sent_at timestamp,
  paid_at timestamp,
  metadata jsonb NOT NULL DEFAULT '{}',
  created_by integer NOT NULL,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS invoices_v2_link_token_uidx ON invoices_v2 (payment_link_token_hash);
CREATE UNIQUE INDEX IF NOT EXISTS invoices_v2_tenant_number_uidx ON invoices_v2 (tenant_id, invoice_number);
CREATE INDEX IF NOT EXISTS invoices_v2_tenant_status_idx ON invoices_v2 (tenant_id, status);

CREATE TABLE IF NOT EXISTS invoice_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id bigint NOT NULL REFERENCES invoices_v2(id),
  description varchar(512) NOT NULL,
  quantity numeric(12,4) NOT NULL,
  unit_price numeric(18,4) NOT NULL,
  amount numeric(18,4) NOT NULL,
  sort_order integer NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS invoice_items_invoice_idx ON invoice_items (invoice_id);

CREATE TABLE IF NOT EXISTS card_funding_intents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(id),
  user_id integer NOT NULL,
  stripe_payment_intent_id varchar(128) NOT NULL,
  purpose varchar(32) NOT NULL,
  purpose_entity_id varchar(64) NOT NULL,
  amount numeric(18,4) NOT NULL,
  currency varchar(3) NOT NULL,
  fee_amount numeric(18,4) NOT NULL DEFAULT 0,
  status varchar(24) NOT NULL DEFAULT 'requires_capture',
  hold_until timestamp,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS card_funding_intents_pi_uidx ON card_funding_intents (stripe_payment_intent_id);
CREATE INDEX IF NOT EXISTS card_funding_intents_purpose_idx ON card_funding_intents (purpose, purpose_entity_id, status);

CREATE TABLE IF NOT EXISTS accounting_connections (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(id),
  provider varchar(32) NOT NULL,
  status varchar(24) NOT NULL DEFAULT 'pending_auth',
  access_token_encrypted text,
  refresh_token_encrypted text,
  realm_id varchar(128),
  expires_at timestamp,
  last_sync_at timestamp,
  sync_cursor varchar(255),
  created_by integer NOT NULL,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS accounting_connections_tenant_provider_uidx ON accounting_connections (tenant_id, provider);

CREATE TABLE IF NOT EXISTS accounting_sync_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  connection_id bigint NOT NULL REFERENCES accounting_connections(id),
  direction varchar(8) NOT NULL,
  entity_type varchar(32) NOT NULL,
  entity_id varchar(64) NOT NULL,
  external_id varchar(128),
  action varchar(32) NOT NULL,
  status varchar(16) NOT NULL,
  error text,
  created_at timestamp NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS accounting_sync_logs_conn_idx ON accounting_sync_logs (connection_id, created_at);

CREATE TABLE IF NOT EXISTS partner_payout_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_tenant_id integer NOT NULL REFERENCES tenants(id),
  idempotency_key varchar(128) NOT NULL,
  payee jsonb NOT NULL,
  amount numeric(18,4) NOT NULL,
  currency varchar(3) NOT NULL,
  corridor varchar(16) NOT NULL,
  rail varchar(32) NOT NULL,
  status varchar(16) NOT NULL DEFAULT 'received',
  settle_ref varchar(255),
  failure_reason text,
  tb_hold_id varchar(64),
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS partner_payout_requests_idem_uidx ON partner_payout_requests (partner_tenant_id, idempotency_key);
CREATE INDEX IF NOT EXISTS partner_payout_requests_status_idx ON partner_payout_requests (status, created_at);

CREATE TABLE IF NOT EXISTS ocr_jobs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(id),
  storage_key varchar(512) NOT NULL,
  source varchar(16) NOT NULL DEFAULT 'upload',
  status varchar(16) NOT NULL DEFAULT 'queued',
  result jsonb,
  confidence numeric(5,4),
  bill_id bigint,
  error text,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ocr_jobs_tenant_status_idx ON ocr_jobs (tenant_id, status);
