-- BDC Operating Platform (Wave: bdc-integration) — SPEC-bdc §2.
-- ADDITIVE ONLY: 19 new bdc_* tables; no existing table/enum/column modified.
-- Monetary convention (orchestrator amendment): numeric(18,2) major units,
-- matching wallets/transactions; SPEC *Minor/*Kobo columns renamed without
-- the suffix. Status fields are varchar with app-layer validation (no new
-- pgEnums); allowed vocabularies noted in comments.

-- 1. Operator profile per tenant (CBN licence, capital, prudential limits).
CREATE TABLE IF NOT EXISTS bdc_operator_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(id),
  tier varchar(8), -- 'tier_1' | 'tier_2'
  license_no varchar(64),
  state_code varchar(8),
  shareholders_funds numeric(18,2) NOT NULL DEFAULT 0.00,
  nop_limit_pct integer NOT NULL DEFAULT 30,
  borrowing_limit_pct integer NOT NULL DEFAULT 50,
  -- Weekly NFEM entitlement in USD; 150000.00 = $150k (SPEC: 15000000 minor units).
  weekly_nfem_entitlement_usd numeric(18,2) NOT NULL DEFAULT 150000.00,
  license_status varchar(16) NOT NULL DEFAULT 'pending', -- 'pending'|'aip'|'provisional'|'active'|'suspended'
  pa_deadline_at timestamp,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS bdc_operator_profiles_tenant_uidx ON bdc_operator_profiles (tenant_id);

-- 2. Branches (Tier-2: <=5 per state, single state_code — enforced in app layer).
CREATE TABLE IF NOT EXISTS bdc_branches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(id),
  code varchar(16),
  name varchar(128),
  address text,
  state_code varchar(8),
  lat numeric(10,7),
  lng numeric(10,7),
  is_head_office boolean DEFAULT false,
  status varchar(16) DEFAULT 'pending', -- 'pending'|'active'|'suspended'|'closed'
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS bdc_branches_tenant_code_uidx ON bdc_branches (tenant_id, code);

-- 3. Franchisees (Tier-1 operators only; 1km geofence — app layer).
CREATE TABLE IF NOT EXISTS bdc_franchisees (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(id), -- franchisor tenant
  name varchar(128),
  license_ref varchar(64),
  state_code varchar(8),
  lat numeric(10,7),
  lng numeric(10,7),
  royalty_bps integer DEFAULT 0,
  status varchar(16) DEFAULT 'pending',
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);

-- 4. Vaults (branch or head-office cash/FX stores).
CREATE TABLE IF NOT EXISTS bdc_vaults (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(id),
  branch_id bigint REFERENCES bdc_branches(id),
  name varchar(64),
  vault_type varchar(16) DEFAULT 'branch_vault', -- 'branch_vault'|'head_vault'
  status varchar(16) DEFAULT 'active',
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);

-- 5. Teller drawers (per-branch cash tills assigned to a holder user).
CREATE TABLE IF NOT EXISTS bdc_teller_drawers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(id),
  branch_id bigint REFERENCES bdc_branches(id),
  holder_user_id integer NOT NULL,
  status varchar(16) DEFAULT 'active',
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);

-- 6. Denomination-level inventory per location (vault/drawer/CIT).
--    version enables optimistic-concurrency guarded stock mutations.
CREATE TABLE IF NOT EXISTS bdc_denomination_inventory (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(id),
  location_type varchar(8), -- 'vault'|'drawer'|'cit'
  location_id bigint NOT NULL,
  currency varchar(3),
  -- Face value per note in major units (e.g. 100.00 = $100 bill).
  denomination numeric(18,2) NOT NULL,
  note_count integer NOT NULL DEFAULT 0,
  version integer NOT NULL DEFAULT 0,
  updated_at timestamp NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS bdc_denomination_inventory_loc_ccy_denom_uidx
  ON bdc_denomination_inventory (tenant_id, location_type, location_id, currency, denomination);

-- 7. Rate bands (max deviation from reference rate, bps, per currency).
--    UNIQUE per (tenant_id, currency) where active — enforced in app layer.
CREATE TABLE IF NOT EXISTS bdc_rate_bands (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(id),
  currency varchar(3),
  band_bps integer NOT NULL,
  active boolean DEFAULT true,
  set_by_user_id integer NOT NULL,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);

-- 8. Rate quotes (maker-checker; rate = naira per 1 FX unit).
CREATE TABLE IF NOT EXISTS bdc_rate_quotes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(id),
  branch_id bigint,
  currency varchar(3),
  side varchar(4), -- 'buy'|'sell'
  rate numeric(18,2) NOT NULL,
  reference_rate numeric(18,2) NOT NULL,
  status varchar(12) DEFAULT 'draft', -- 'draft'|'published'|'expired'|'suspended'
  maker_id integer NOT NULL,
  checker_id integer,
  published_at timestamp,
  expires_at timestamp,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);

-- 9. BDC customers (walk-in / platform-linked; BVN secretBox-encrypted).
CREATE TABLE IF NOT EXISTS bdc_customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(id),
  customer_type varchar(12), -- 'resident'|'non_resident'
  full_name varchar(255),
  bvn_enc text, -- secretBox-encrypted via encryptField
  tin varchar(32),
  passport_no varchar(32),
  mrz_data jsonb,
  risk_rating varchar(12) DEFAULT 'standard', -- 'low'|'standard'|'high'
  pep_flag boolean DEFAULT false,
  kyc_status varchar(16) DEFAULT 'pending', -- 'pending'|'verified'|'rejected'
  platform_user_id integer,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);

-- 10. Source-of-funds declarations (mandatory >= $10k FX purchases).
CREATE TABLE IF NOT EXISTS bdc_sof_declarations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(id),
  customer_id bigint REFERENCES bdc_customers(id),
  transaction_id bigint,
  amount_usd numeric(18,2) NOT NULL,
  source_description text,
  document_refs jsonb NOT NULL DEFAULT '[]',
  status varchar(12) DEFAULT 'submitted', -- 'submitted'|'approved'|'rejected'
  reviewed_by integer,
  reviewed_at timestamp,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);

-- 11. BDC transactions (buy/sell FX, IMTO payout, NFEM purchase/return).
--     payment_leg: {method:'cash'|'nip_transfer'|'prepaid_card'|'domiciliary', reference:string|null}
CREATE TABLE IF NOT EXISTS bdc_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(id),
  branch_id bigint REFERENCES bdc_branches(id),
  txn_type varchar(16), -- 'buy_fx'|'sell_fx'|'imto_payout'|'nfem_purchase'|'nfem_return'
  currency varchar(3),
  fx_amount numeric(18,2) NOT NULL,
  naira_amount numeric(18,2) NOT NULL,
  rate numeric(18,2) NOT NULL,
  purpose_code varchar(32),
  evidence_refs jsonb NOT NULL DEFAULT '[]',
  customer_id bigint REFERENCES bdc_customers(id),
  payment_leg jsonb NOT NULL,
  cash_portion numeric(18,2) NOT NULL DEFAULT 0.00,
  idempotency_key varchar(96) NOT NULL,
  tb_transfer_ids jsonb NOT NULL DEFAULT '[]',
  status varchar(12) DEFAULT 'pending', -- 'pending'|'posted'|'settled'|'failed'|'reversed'
  maker_id integer NOT NULL,
  checker_id integer,
  failure_reason text,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS bdc_transactions_idempotency_key_uidx ON bdc_transactions (idempotency_key);
CREATE INDEX IF NOT EXISTS bdc_transactions_tenant_status_idx ON bdc_transactions (tenant_id, status);
CREATE INDEX IF NOT EXISTS bdc_transactions_tenant_created_at_idx ON bdc_transactions (tenant_id, created_at);

-- 12. NFEM weekly entitlements per bank (cap/used in USD; version-guarded).
CREATE TABLE IF NOT EXISTS bdc_nfem_entitlements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(id),
  bank_code varchar(16),
  week_start date NOT NULL,
  cap_usd numeric(18,2) NOT NULL,
  used_usd numeric(18,2) NOT NULL DEFAULT 0.00,
  version integer NOT NULL DEFAULT 0,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS bdc_nfem_entitlements_tenant_bank_week_uidx
  ON bdc_nfem_entitlements (tenant_id, bank_code, week_start);

-- 13. NFEM purchase batches (24h liquidation deadline after funding).
CREATE TABLE IF NOT EXISTS bdc_nfem_purchase_batches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(id),
  entitlement_id bigint REFERENCES bdc_nfem_entitlements(id),
  amount_usd numeric(18,2) NOT NULL,
  rate numeric(18,2) NOT NULL,
  naira_paid numeric(18,2) NOT NULL,
  fxbt_reference varchar(64),
  status varchar(12) DEFAULT 'requested', -- 'requested'|'funded'|'selling'|'liquidated'|'returned'|'expired'
  purchased_at timestamp,
  deadline_at timestamp,
  liquidated_at timestamp,
  temporal_workflow_id varchar(96),
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);

-- 14. Position snapshots (EOD NOP/borrowing vs prudential caps).
CREATE TABLE IF NOT EXISTS bdc_position_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(id),
  snapshot_at timestamp NOT NULL DEFAULT now(),
  nop_usd numeric(18,2) NOT NULL,
  nop_pct numeric(6,2),
  borrowing numeric(18,2) NOT NULL DEFAULT 0.00,
  borrowing_pct numeric(6,2),
  breach_flags jsonb NOT NULL DEFAULT '[]',
  created_at timestamp NOT NULL DEFAULT now()
);

-- 15. CIT manifests (dual-custodian cash-in-transit transfers).
--     items: [{currency, denomination, noteCount}]
CREATE TABLE IF NOT EXISTS bdc_cit_manifests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(id),
  from_location jsonb NOT NULL,
  to_location jsonb NOT NULL,
  items jsonb NOT NULL,
  custodian_a_id integer NOT NULL,
  custodian_b_id integer NOT NULL,
  status varchar(12) DEFAULT 'draft', -- 'draft'|'in_transit'|'delivered'|'disputed'
  dispatched_at timestamp,
  delivered_at timestamp,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);

-- 16. Counterfeit note register (quarantine / handover to authorities).
CREATE TABLE IF NOT EXISTS bdc_counterfeit_register (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(id),
  branch_id bigint REFERENCES bdc_branches(id),
  currency varchar(3),
  denomination numeric(18,2),
  note_serial varchar(64),
  detected_by_user_id integer,
  disposition varchar(24) DEFAULT 'quarantined', -- 'quarantined'|'handed_to_authorities'
  notes text,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);

-- 17. Regulatory returns (FIFX/FinA/CARP/TRMS/extranet staging + submission).
CREATE TABLE IF NOT EXISTS bdc_regulatory_returns (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(id),
  return_type varchar(10), -- 'fifx'|'fina'|'carp'|'trms'|'extranet'
  period_start date NOT NULL,
  period_end date NOT NULL,
  payload jsonb,
  format_version varchar(16) DEFAULT 'v1',
  status varchar(12) DEFAULT 'draft', -- 'draft'|'staged'|'submitted'|'acknowledged'|'quarantined'|'failed'
  submitted_at timestamp,
  ack_ref varchar(96),
  ack_at timestamp,
  error_detail text,
  idempotency_key varchar(96) NOT NULL,
  temporal_workflow_id varchar(96),
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS bdc_regulatory_returns_idempotency_key_uidx ON bdc_regulatory_returns (idempotency_key);

-- 18. IMTO settlement accruals (per-payout commission + naira leg tracking).
CREATE TABLE IF NOT EXISTS bdc_imto_settlements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(id),
  imto_code varchar(32),
  mojaloop_transfer_id varchar(96),
  fx_amount numeric(18,2) NOT NULL,
  naira_paid numeric(18,2) NOT NULL,
  commission numeric(18,2) NOT NULL DEFAULT 0.00,
  status varchar(12) DEFAULT 'accrued', -- 'accrued'|'settled'|'disputed'
  statement_ref varchar(64),
  settled_at timestamp,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);

-- 19. IMTO commission schedules (tiered bps by USD amount band).
CREATE TABLE IF NOT EXISTS bdc_commission_schedules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL REFERENCES tenants(id),
  imto_code varchar(32),
  tier_min_usd numeric(18,2) NOT NULL DEFAULT 0.00,
  tier_max_usd numeric(18,2) NOT NULL,
  commission_bps integer NOT NULL,
  active boolean DEFAULT true,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);
