-- 0091_wave12.sql — SPEC-wave12 §2. ADDITIVE ONLY: new tables + additive columns.
-- No drops, no renames, no enum edits, no modifications to existing columns/indexes.

CREATE TABLE IF NOT EXISTS bdc_reversals (
  id              bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tenant_id       integer NOT NULL REFERENCES tenants(id),
  txn_id          bigint NOT NULL REFERENCES bdc_transactions(id),
  reversal_type   varchar(16) NOT NULL,            -- 'manual'|'rail_return'|'recall'
  status          varchar(16) NOT NULL DEFAULT 'requested', -- 'requested'|'approved'|'posted'|'failed'|'rejected'
  reason          text NOT NULL,
  rail_reference  varchar(128),
  requested_by    integer NOT NULL,
  approved_by     integer,
  tb_reversal_ids jsonb NOT NULL DEFAULT '[]',
  failure_reason  text,
  created_at      timestamp NOT NULL DEFAULT NOW(),
  updated_at      timestamp NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS bdc_reversals_tenant_txn_idx ON bdc_reversals(tenant_id, txn_id);
CREATE INDEX IF NOT EXISTS bdc_reversals_status_idx ON bdc_reversals(status) WHERE status IN ('requested','approved');

CREATE TABLE IF NOT EXISTS bdc_pickup_authorizations (
  id                bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tenant_id         integer NOT NULL REFERENCES tenants(id),
  customer_id       bigint NOT NULL REFERENCES bdc_customers(id),
  txn_id            bigint REFERENCES bdc_transactions(id),
  agent_full_name   varchar(255) NOT NULL,
  agent_id_type     varchar(32) NOT NULL,          -- 'nin'|'bvn'|'passport'|'drivers_license'|'voters_card'
  agent_id_number_enc text NOT NULL,               -- secretBox-encrypted
  relationship      varchar(64) NOT NULL,
  status            varchar(16) NOT NULL DEFAULT 'pending', -- 'pending'|'used'|'expired'|'revoked'
  max_amount        numeric(18,2),
  expires_at        timestamp NOT NULL,
  used_at           timestamp,
  used_by           integer,
  created_by        integer NOT NULL,
  idempotency_key   varchar(96) NOT NULL,
  created_at        timestamp NOT NULL DEFAULT NOW(),
  updated_at        timestamp NOT NULL DEFAULT NOW(),
  CONSTRAINT bdc_pickup_auth_tenant_idem_uidx UNIQUE (tenant_id, idempotency_key)
);
CREATE INDEX IF NOT EXISTS bdc_pickup_auth_customer_idx ON bdc_pickup_authorizations(tenant_id, customer_id, status);

CREATE TABLE IF NOT EXISTS bdc_rescreening_results (
  id            bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tenant_id     integer NOT NULL REFERENCES tenants(id),
  customer_id   bigint NOT NULL REFERENCES bdc_customers(id),
  run_id        varchar(64) NOT NULL,
  verdict       varchar(16) NOT NULL,             -- 'clear'|'match'|'error'
  score         numeric(5,4),
  matched_lists jsonb NOT NULL DEFAULT '[]',
  blocked       boolean NOT NULL DEFAULT false,
  report        jsonb,
  created_at    timestamp NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS bdc_rescreen_latest_idx ON bdc_rescreening_results(tenant_id, customer_id, created_at DESC);
CREATE INDEX IF NOT EXISTS bdc_rescreen_blocked_idx ON bdc_rescreening_results(tenant_id, blocked) WHERE blocked = true;

CREATE TABLE IF NOT EXISTS bdc_structuring_alerts (
  id            bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tenant_id     integer NOT NULL REFERENCES tenants(id),
  customer_id   bigint NOT NULL REFERENCES bdc_customers(id),
  window_days   integer NOT NULL,                 -- 7 | 30
  window_start  date NOT NULL,
  total_usd     numeric(18,2) NOT NULL,
  txn_count     integer NOT NULL,
  disposition   varchar(16) NOT NULL DEFAULT 'open', -- 'open'|'sof_required'|'str_filed'|'dismissed'
  created_at    timestamp NOT NULL DEFAULT NOW(),
  updated_at    timestamp NOT NULL DEFAULT NOW(),
  CONSTRAINT bdc_structuring_unique UNIQUE (tenant_id, customer_id, window_days, window_start)
);

CREATE TABLE IF NOT EXISTS bdc_tenant_offboardings (
  id            bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tenant_id     integer NOT NULL REFERENCES tenants(id) UNIQUE,
  status        varchar(16) NOT NULL DEFAULT 'requested', -- 'requested'|'in_progress'|'blocked'|'completed'
  blockers      jsonb NOT NULL DEFAULT '[]',
  initiated_by  integer NOT NULL,
  completed_at  timestamp,
  created_at    timestamp NOT NULL DEFAULT NOW(),
  updated_at    timestamp NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS teller_fraud_signals (
  id            bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tenant_id     integer NOT NULL REFERENCES tenants(id),
  teller_user_id integer NOT NULL,
  window_start  date NOT NULL,
  window_end    date NOT NULL,
  signal_type   varchar(32) NOT NULL,  -- 'variance_pattern'|'out_of_hours'|'reversal_concentration'|'counterfeit_concentration'
  score         numeric(6,3) NOT NULL,
  evidence      jsonb NOT NULL,
  status        varchar(16) NOT NULL DEFAULT 'open', -- 'open'|'reviewing'|'escalated'|'cleared'
  created_at    timestamp NOT NULL DEFAULT NOW(),
  CONSTRAINT teller_fraud_unique UNIQUE (tenant_id, teller_user_id, signal_type, window_start)
);

CREATE TABLE IF NOT EXISTS stablecoin_settlement_events (
  id            bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  event_id      varchar(128) NOT NULL UNIQUE,
  tx_ref        varchar(128) NOT NULL,
  provider      varchar(32) NOT NULL,
  status        varchar(16) NOT NULL,             -- 'pending'|'processing'|'completed'|'failed'
  raw_status    varchar(64),
  applied       boolean NOT NULL DEFAULT false,
  payload       jsonb NOT NULL,
  received_at   timestamp NOT NULL DEFAULT NOW(),
  applied_at    timestamp
);
CREATE INDEX IF NOT EXISTS stablecoin_settle_events_txref_idx ON stablecoin_settlement_events(tx_ref);

-- G5 additive columns (NFEM partial disbursement)
ALTER TABLE bdc_nfem_purchase_batches ADD COLUMN IF NOT EXISTS actual_disbursed_usd numeric(18,2);
ALTER TABLE bdc_nfem_purchase_batches ADD COLUMN IF NOT EXISTS residual_handling varchar(16); -- 'returned'|'expired'|null
