-- 0092_wave13.sql — Stakeholder onboarding robustness (additive only; idempotent)
-- Existing tables/enums are NOT modified except ADD COLUMN IF NOT EXISTS / new indexes.
-- 1. users.tenant_id — fixes resolveTenantContext reading a nonexistent column (F-T1).
ALTER TABLE users ADD COLUMN IF NOT EXISTS tenant_id integer REFERENCES tenants(id);
CREATE INDEX IF NOT EXISTS users_tenant_id_idx ON users(tenant_id);

-- 2. partner_applications.claim_token — closes unauthenticated-claim hole (F-T3).
ALTER TABLE partner_applications ADD COLUMN IF NOT EXISTS claim_token varchar(64);
CREATE INDEX IF NOT EXISTS partner_applications_claim_token_idx ON partner_applications(claim_token);

-- 3. Idempotency constraints (additive unique indexes).
CREATE UNIQUE INDEX IF NOT EXISTS merchant_kyb_reviews_user_uniq ON merchant_kyb_reviews(user_id);
CREATE UNIQUE INDEX IF NOT EXISTS tenant_users_uniq ON tenant_users(tenant_id, user_id);

-- 4. merchants — real merchant entity activated by KYB approval.
CREATE TABLE IF NOT EXISTS merchants (
  id                serial PRIMARY KEY,
  tenant_id         integer REFERENCES tenants(id),
  user_id           integer NOT NULL REFERENCES users(id),
  kyb_record_id     integer,
  business_name     varchar(200) NOT NULL,
  country           varchar(2),
  status            varchar(20) NOT NULL DEFAULT 'pending_kyb', -- 'pending_kyb'|'active'|'suspended'|'rejected'
  risk_rating       varchar(10) NOT NULL DEFAULT 'medium',
  terms_accepted_at timestamp,
  terms_version     varchar(20),
  created_at        timestamp NOT NULL DEFAULT now(),
  updated_at        timestamp NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS merchants_user_uniq ON merchants(user_id);
CREATE INDEX IF NOT EXISTS merchants_tenant_idx ON merchants(tenant_id, status);

-- 5. merchant_directors — UBO/director register with screening verdict.
CREATE TABLE IF NOT EXISTS merchant_directors (
  id                serial PRIMARY KEY,
  merchant_id       integer NOT NULL REFERENCES merchants(id),
  full_name         varchar(200) NOT NULL,
  id_doc_url        text,
  is_ubo            boolean NOT NULL DEFAULT false,
  ownership_pct     numeric(5,2),
  screening_verdict varchar(16), -- 'clear'|'match'|'error'|NULL (pending)
  created_at        timestamp NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS merchant_directors_merchant_idx ON merchant_directors(merchant_id);

-- 6. bdc_tellers — teller registration (float assignment uses existing bdc_teller_drawers).
CREATE TABLE IF NOT EXISTS bdc_tellers (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id       integer NOT NULL REFERENCES tenants(id),
  branch_id       bigint NOT NULL REFERENCES bdc_branches(id),
  teller_user_id  integer NOT NULL REFERENCES users(id),
  display_name    varchar(120),
  status          varchar(16) NOT NULL DEFAULT 'pending', -- 'pending'|'active'|'suspended'
  created_at      timestamp NOT NULL DEFAULT now(),
  updated_at      timestamp NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS bdc_tellers_uniq ON bdc_tellers(tenant_id, teller_user_id);
CREATE INDEX IF NOT EXISTS bdc_tellers_branch_idx ON bdc_tellers(branch_id, status);
