apiVersion: apisix.apache.org/v2
kind: ApisixClusterConfig
metadata:
  name: apisix-cluster-config-ha
  namespace: apisix
spec:
  admin:
    adminKey: ""
    baseURL: http://apisix-admin.apisix.svc.cluster.local:9180/apisix/admin
  etcd:
    prefix: /apisix
    host:
    - http://etcd.apisix.svc.cluster.local:2379
