# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import payment_gateway_service_pb2 as payment__gateway__service__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in payment_gateway_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaymentGatewayServiceStub(object):
    """The payment gateway service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitiatePayment = channel.unary_unary(
                '/payment_gateway_service.PaymentGatewayService/InitiatePayment',
                request_serializer=payment__gateway__service__pb2.InitiatePaymentRequest.SerializeToString,
                response_deserializer=payment__gateway__service__pb2.InitiatePaymentResponse.FromString,
                _registered_method=True)
        self.VerifyPayment = channel.unary_unary(
                '/payment_gateway_service.PaymentGatewayService/VerifyPayment',
                request_serializer=payment__gateway__service__pb2.VerifyPaymentRequest.SerializeToString,
                response_deserializer=payment__gateway__service__pb2.VerifyPaymentResponse.FromString,
                _registered_method=True)
        self.RefundPayment = channel.unary_unary(
                '/payment_gateway_service.PaymentGatewayService/RefundPayment',
                request_serializer=payment__gateway__service__pb2.RefundPaymentRequest.SerializeToString,
                response_deserializer=payment__gateway__service__pb2.RefundPaymentResponse.FromString,
                _registered_method=True)
        self.GetExchangeRate = channel.unary_unary(
                '/payment_gateway_service.PaymentGatewayService/GetExchangeRate',
                request_serializer=payment__gateway__service__pb2.GetExchangeRateRequest.SerializeToString,
                response_deserializer=payment__gateway__service__pb2.GetExchangeRateResponse.FromString,
                _registered_method=True)
        self.CalculateFee = channel.unary_unary(
                '/payment_gateway_service.PaymentGatewayService/CalculateFee',
                request_serializer=payment__gateway__service__pb2.CalculateFeeRequest.SerializeToString,
                response_deserializer=payment__gateway__service__pb2.CalculateFeeResponse.FromString,
                _registered_method=True)
        self.ValidateBankAccount = channel.unary_unary(
                '/payment_gateway_service.PaymentGatewayService/ValidateBankAccount',
                request_serializer=payment__gateway__service__pb2.ValidateBankAccountRequest.SerializeToString,
                response_deserializer=payment__gateway__service__pb2.ValidateBankAccountResponse.FromString,
                _registered_method=True)


class PaymentGatewayServiceServicer(object):
    """The payment gateway service definition.
    """

    def InitiatePayment(self, request, context):
        """Initiates a payment with a specified gateway.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyPayment(self, request, context):
        """Verifies the status of a payment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefundPayment(self, request, context):
        """Refunds a previously made payment.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExchangeRate(self, request, context):
        """Gets the current exchange rate between two currencies.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateFee(self, request, context):
        """Calculates the fee for a transaction.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateBankAccount(self, request, context):
        """Validates a bank account.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentGatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitiatePayment': grpc.unary_unary_rpc_method_handler(
                    servicer.InitiatePayment,
                    request_deserializer=payment__gateway__service__pb2.InitiatePaymentRequest.FromString,
                    response_serializer=payment__gateway__service__pb2.InitiatePaymentResponse.SerializeToString,
            ),
            'VerifyPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyPayment,
                    request_deserializer=payment__gateway__service__pb2.VerifyPaymentRequest.FromString,
                    response_serializer=payment__gateway__service__pb2.VerifyPaymentResponse.SerializeToString,
            ),
            'RefundPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.RefundPayment,
                    request_deserializer=payment__gateway__service__pb2.RefundPaymentRequest.FromString,
                    response_serializer=payment__gateway__service__pb2.RefundPaymentResponse.SerializeToString,
            ),
            'GetExchangeRate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExchangeRate,
                    request_deserializer=payment__gateway__service__pb2.GetExchangeRateRequest.FromString,
                    response_serializer=payment__gateway__service__pb2.GetExchangeRateResponse.SerializeToString,
            ),
            'CalculateFee': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateFee,
                    request_deserializer=payment__gateway__service__pb2.CalculateFeeRequest.FromString,
                    response_serializer=payment__gateway__service__pb2.CalculateFeeResponse.SerializeToString,
            ),
            'ValidateBankAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateBankAccount,
                    request_deserializer=payment__gateway__service__pb2.ValidateBankAccountRequest.FromString,
                    response_serializer=payment__gateway__service__pb2.ValidateBankAccountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payment_gateway_service.PaymentGatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('payment_gateway_service.PaymentGatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentGatewayService(object):
    """The payment gateway service definition.
    """

    @staticmethod
    def InitiatePayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment_gateway_service.PaymentGatewayService/InitiatePayment',
            payment__gateway__service__pb2.InitiatePaymentRequest.SerializeToString,
            payment__gateway__service__pb2.InitiatePaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment_gateway_service.PaymentGatewayService/VerifyPayment',
            payment__gateway__service__pb2.VerifyPaymentRequest.SerializeToString,
            payment__gateway__service__pb2.VerifyPaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefundPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment_gateway_service.PaymentGatewayService/RefundPayment',
            payment__gateway__service__pb2.RefundPaymentRequest.SerializeToString,
            payment__gateway__service__pb2.RefundPaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExchangeRate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment_gateway_service.PaymentGatewayService/GetExchangeRate',
            payment__gateway__service__pb2.GetExchangeRateRequest.SerializeToString,
            payment__gateway__service__pb2.GetExchangeRateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateFee(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment_gateway_service.PaymentGatewayService/CalculateFee',
            payment__gateway__service__pb2.CalculateFeeRequest.SerializeToString,
            payment__gateway__service__pb2.CalculateFeeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateBankAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment_gateway_service.PaymentGatewayService/ValidateBankAccount',
            payment__gateway__service__pb2.ValidateBankAccountRequest.SerializeToString,
            payment__gateway__service__pb2.ValidateBankAccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
