FROM golang:1.21-alpine AS builder

WORKDIR /app

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build application
RUN CGO_ENABLED=0 GOOS=linux go build -o grpc-server ./cmd/grpc

FROM alpine:latest

WORKDIR /app

# Copy binary from builder
COPY --from=builder /app/grpc-server .

# Expose port
EXPOSE 50051

# Run application
CMD ["./grpc-server"]
