from datetime import datetime
from typing import Optional, Any
from pydantic import BaseModel, Field
from .models import VerificationType, VerificationStatus

# --- Custom Exceptions Schemas ---
class APIExceptionSchema(BaseModel):
    """Base schema for all API error responses."""
    detail: str = Field(..., description="A detailed message about the error.")
    code: str = Field(..., description="A unique, machine-readable error code.")

# --- Partner Schemas (Internal/Admin Use) ---
class PartnerBase(BaseModel):
    name: str = Field(..., min_length=3, max_length=255, description="Name of the partner organization.")
    is_active: bool = Field(True, description="Whether the partner's API key is active.")

class PartnerCreate(PartnerBase):
    # API key will be generated by the service, not provided on creation
    pass

class PartnerResponse(PartnerBase):
    id: int
    api_key: Optional[str] = Field(None, description="The API key (only returned on creation).")
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True

# --- Verification Request Schemas ---

class VerificationRequestBase(BaseModel):
    external_ref_id: str = Field(..., max_length=255, description="Unique ID for this request from the partner's system.")
    verification_type: VerificationType = Field(..., description="Type of verification: KYC (Know Your Customer) or KYB (Know Your Business).")
    subject_data: dict[str, Any] = Field(..., description="JSON payload containing the subject's data (e.g., name, address, documents).")

class VerificationRequestCreate(VerificationRequestBase):
    pass

class VerificationRequestUpdate(BaseModel):
    status: Optional[VerificationStatus] = Field(None, description="New status for the verification request.")
    result_details: Optional[dict[str, Any]] = Field(None, description="JSON payload containing the final verification result details.")

class VerificationRequestResponse(VerificationRequestBase):
    id: int
    partner_id: int
    status: VerificationStatus
    result_details: Optional[dict[str, Any]] = Field(None, description="JSON payload containing the final verification result details.")
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True

class VerificationRequestListResponse(BaseModel):
    total: int
    requests: list[VerificationRequestResponse]

# --- Authentication Schemas ---
class APIKeyAuth(BaseModel):
    api_key: str = Field(..., description="The partner's API key for authentication.")