import enum
from datetime import datetime
from sqlalchemy import Column, Integer, String, DateTime, Enum, Numeric, Boolean, ForeignKey, JSON
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class TransactionStatus(enum.Enum):
    PENDING = "PENDING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    REFUNDED = "REFUNDED"
    EXPIRED = "EXPIRED"

class RefundStatus(enum.Enum):
    PENDING = "PENDING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"

class Transaction(Base):
    __tablename__ = "transactions"

    id = Column(Integer, primary_key=True, index=True)
    order_id = Column(String, unique=True, index=True, nullable=False, doc="Unique ID generated by the merchant/system")
    transaction_id = Column(String, unique=True, index=True, nullable=True, doc="Unique ID from the Payment Gateway (PG)")
    amount = Column(Numeric(10, 2), nullable=False, doc="Transaction amount")
    currency = Column(String, default="INR", nullable=False, doc="Currency code (e.g., 'INR')")
    status = Column(Enum(TransactionStatus), default=TransactionStatus.PENDING, nullable=False, doc="Current status of the transaction")
    vpa = Column(String, nullable=False, doc="Virtual Payment Address (UPI ID) of the payer")
    gateway_response = Column(JSON, nullable=True, doc="Raw response from the Payment Gateway")
    user_id = Column(Integer, index=True, nullable=True, doc="Foreign key to the User entity (if applicable)")

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    refunds = relationship("Refund", back_populates="transaction")

class Refund(Base):
    __tablename__ = "refunds"

    id = Column(Integer, primary_key=True, index=True)
    transaction_id = Column(Integer, ForeignKey("transactions.id"), index=True, nullable=False, doc="Foreign key to the Transaction entity")
    refund_id = Column(String, unique=True, index=True, nullable=False, doc="Unique ID from the Payment Gateway for the refund")
    amount = Column(Numeric(10, 2), nullable=False, doc="Refund amount")
    status = Column(Enum(RefundStatus), default=RefundStatus.PENDING, nullable=False, doc="Status of the refund")
    gateway_response = Column(JSON, nullable=True, doc="Raw response from the Payment Gateway")

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    transaction = relationship("Transaction", back_populates="refunds")

class WebhookEvent(Base):
    __tablename__ = "webhook_events"

    id = Column(Integer, primary_key=True, index=True)
    event_id = Column(String, unique=True, index=True, nullable=False, doc="Unique ID for the event from the PG")
    event_type = Column(String, nullable=False, doc="Type of event (e.g., 'payment.captured', 'refund.processed')")
    payload = Column(JSON, nullable=False, doc="Full payload of the webhook event")
    processed = Column(Boolean, default=False, nullable=False, doc="Flag indicating if the event has been processed by the service")
    
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)