remitflow_lakehouse:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: spark-master
      port: 10000
      schema: remitflow
      threads: 4
    prod:
      type: spark
      method: thrift
      host: "{{ env_var('SPARK_THRIFT_HOST') }}"
      port: "{{ env_var('SPARK_THRIFT_PORT', '10000') | int }}"
      schema: remitflow
      threads: 8
