apiVersion: v1
kind: Service
metadata:
  name: {{ include "outbound-swift.fullname" . }}
  labels:
    {{- include "outbound-swift.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "outbound-swift.selectorLabels" . | nindent 4 }}
