import enum
from datetime import datetime
from decimal import Decimal

from sqlalchemy import Column, Integer, String, DateTime, Boolean, Enum, ForeignKey, Numeric, Index
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class TransactionStatus(enum.Enum):
    PENDING = "PENDING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    REVERSED = "REVERSED"
    TIMEOUT = "TIMEOUT"

class Bank(Base):
    __tablename__ = "banks"

    id = Column(Integer, primary_key=True, index=True)
    bank_code = Column(String, unique=True, index=True, nullable=False, doc="NIBSS Bank Code (e.g., 044)")
    bank_name = Column(String, nullable=False, doc="Full name of the bank")
    cbn_code = Column(String, nullable=True, doc="Central Bank of Nigeria code")
    is_active = Column(Boolean, default=True, nullable=False)

    # Relationships
    transactions = relationship("Transaction", back_populates="destination_bank", foreign_keys="[Transaction.destination_bank_code]")
    name_enquiries = relationship("NameEnquiry", back_populates="bank", foreign_keys="[NameEnquiry.bank_code]")

    def __repr__(self):
        return f"<Bank(bank_code='{self.bank_code}', bank_name='{self.bank_name}')>"

class NameEnquiry(Base):
    __tablename__ = "name_enquiries"

    id = Column(Integer, primary_key=True, index=True)
    account_number = Column(String, index=True, nullable=False)
    bank_code = Column(String, ForeignKey("banks.bank_code"), nullable=False)
    
    # NIBSS Response Fields
    account_name = Column(String, nullable=False)
    bvn = Column(String, nullable=True, doc="Bank Verification Number")
    response_code = Column(String, nullable=False, doc="NIBSS response code")
    response_message = Column(String, nullable=False)

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # Relationships
    bank = relationship("Bank", back_populates="name_enquiries", foreign_keys=[bank_code])

    def __repr__(self):
        return f"<NameEnquiry(account='{self.account_number}', name='{self.account_name}')>"

class Transaction(Base):
    __tablename__ = "transactions"

    id = Column(Integer, primary_key=True, index=True)
    transaction_ref = Column(String, unique=True, index=True, nullable=False, doc="Unique reference generated by our system")
    nibss_session_id = Column(String, unique=True, index=True, nullable=True, doc="Session ID returned by NIBSS")
    
    # Transaction Details
    source_account_number = Column(String, nullable=False)
    destination_account_number = Column(String, nullable=False)
    destination_bank_code = Column(String, ForeignKey("banks.bank_code"), nullable=False)
    amount = Column(Numeric(18, 2), nullable=False)
    narration = Column(String, nullable=True)
    
    # Status and Response
    status = Column(Enum(TransactionStatus), default=TransactionStatus.PENDING, index=True, nullable=False)
    response_code = Column(String, nullable=True, doc="NIBSS response code (e.g., '00')")
    response_message = Column(String, nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    # Relationships
    destination_bank = relationship("Bank", back_populates="transactions", foreign_keys=[destination_bank_code])

    __table_args__ = (
        Index('idx_transaction_status_created', status, created_at),
    )

    def __repr__(self):
        return f"<Transaction(ref='{self.transaction_ref}', amount='{self.amount}', status='{self.status.value}')>"
