from datetime import datetime
from decimal import Decimal
from typing import Optional, List
from pydantic import BaseModel, Field, validator

from models import TransactionStatus

# --- Bank Schemas ---

class BankBase(BaseModel):
    bank_code: str = Field(..., max_length=3, description="NIBSS Bank Code (3 digits)")
    bank_name: str = Field(..., description="Full name of the bank")

class BankCreate(BankBase):
    cbn_code: Optional[str] = Field(None, description="Central Bank of Nigeria code")
    is_active: bool = Field(True, description="Whether the bank is active for NIP")

class Bank(BankBase):
    id: int
    cbn_code: Optional[str]
    is_active: bool

    class Config:
        orm_mode = True

# --- Name Enquiry Schemas ---

class NameEnquiryRequest(BaseModel):
    account_number: str = Field(..., max_length=10, description="10-digit account number")
    bank_code: str = Field(..., max_length=3, description="3-digit NIBSS bank code")

class NameEnquiryResponse(BaseModel):
    account_number: str
    bank_code: str
    account_name: str = Field(..., description="Account name returned by NIBSS")
    bvn: Optional[str] = Field(None, description="Bank Verification Number")
    response_code: str = Field(..., description="NIBSS response code (e.g., '00')")
    response_message: str

    class Config:
        orm_mode = True

# --- Transaction Schemas ---

class TransactionBase(BaseModel):
    destination_account_number: str = Field(..., max_length=10, description="10-digit beneficiary account number")
    destination_bank_code: str = Field(..., max_length=3, description="3-digit NIBSS bank code")
    amount: Decimal = Field(..., gt=0, max_digits=18, decimal_places=2, description="Transaction amount in Naira")
    narration: Optional[str] = Field(None, max_length=100, description="Transaction narration")

    @validator('amount')
    def validate_amount(cls, v) -> None:
        if v <= Decimal('0.00'):
            raise ValueError('Amount must be greater than zero')
        return v

class TransactionCreate(TransactionBase):
    source_account_number: str = Field(..., max_length=10, description="10-digit source account number")

class TransactionUpdate(BaseModel):
    # Only status and response fields are typically updated externally
    status: TransactionStatus
    response_code: Optional[str]
    response_message: Optional[str]

class Transaction(TransactionBase):
    id: int
    transaction_ref: str = Field(..., description="Unique reference generated by our system")
    nibss_session_id: Optional[str] = Field(None, description="Session ID returned by NIBSS")
    source_account_number: str
    status: TransactionStatus
    response_code: Optional[str]
    response_message: Optional[str]
    created_at: datetime
    updated_at: datetime

    class Config:
        orm_mode = True
        use_enum_values = True

class TransactionListResponse(BaseModel):
    total: int
    page: int
    size: int
    items: List[Transaction]
