---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: transactions-binding
  namespace: remitflow
spec:
  type: bindings.kafka
  version: v1
  metadata:
    - name: brokers
      value: "kafka:9092"
    - name: topics
      value: "remitflow.transactions"
    - name: consumerGroup
      value: "remitflow-transaction-consumer"
    - name: publishTopic
      value: "remitflow.transactions"
    - name: authRequired
      value: "false"
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kyc-events-binding
  namespace: remitflow
spec:
  type: bindings.kafka
  version: v1
  metadata:
    - name: brokers
      value: "kafka:9092"
    - name: topics
      value: "remitflow.kyc.events"
    - name: consumerGroup
      value: "remitflow-kyc-consumer"
    - name: publishTopic
      value: "remitflow.kyc.events"
    - name: authRequired
      value: "false"
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: fx-rates-binding
  namespace: remitflow
spec:
  type: bindings.kafka
  version: v1
  metadata:
    - name: brokers
      value: "kafka:9092"
    - name: topics
      value: "remitflow.fx.rates"
    - name: consumerGroup
      value: "remitflow-fx-consumer"
    - name: publishTopic
      value: "remitflow.fx.rates"
    - name: authRequired
      value: "false"
