apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: remitflow-pubsub
  namespace: remitflow
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: "kafka-0:29092,kafka-1:29092,kafka-2:29092"
    - name: consumerGroup
      value: "remitflow-dapr"
    - name: clientID
      value: "remitflow-dapr-client"
    - name: authRequired
      value: "false"
    - name: initialOffset
      value: "newest"
    - name: maxMessageBytes
      value: "10485760"
    - name: consumeRetryInterval
      value: "100ms"
    - name: consumeRetryEnabled
      value: "true"
    - name: producerRequiredAcks
      value: "all"
    - name: producerCompression
      value: "lz4"
    - name: producerMaxMessageBytes
      value: "10485760"
    - name: clientConnectionKeepAliveInterval
      value: "30s"
    - name: clientConnectionTopicMetadataRefreshInterval
      value: "5m"
