apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: remitflow-statestore
  namespace: remitflow
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: "redis-cluster:6379"
    - name: redisPassword
      secretKeyRef:
        name: remitflow-secrets
        key: redis-password
    - name: enableTLS
      value: "false"
    - name: maxRetries
      value: "5"
    - name: maxRetryBackoff
      value: "2s"
    - name: ttlInSeconds
      value: "3600"
    - name: keyPrefix
      value: "remitflow"
    - name: processingTimeout
      value: "30s"
    - name: redeliverInterval
      value: "15s"
    - name: queryIndexes
      value: '[{"name":"userId","jsonPath":"$.userId"},{"name":"corridorKey","jsonPath":"$.corridorKey"}]'
auth:
  secretStore: kubernetes
