#!/usr/bin/env python3
"""
RemitFlow Secure Secret Generator
Generates cryptographically secure random values for all required environment variables.
Run once during initial setup: python3 scripts/generate_secrets.py > .env.generated
"""
import secrets
import base64
import os


def generate_hex(bytes_count: int = 32) -> str:
    return secrets.token_hex(bytes_count)


def generate_urlsafe(bytes_count: int = 32) -> str:
    return secrets.token_urlsafe(bytes_count)


def generate_fernet_key() -> str:
    """Generate a valid Fernet encryption key (32 bytes, base64-encoded)."""
    key = secrets.token_bytes(32)
    return base64.urlsafe_b64encode(key).decode()


def generate_password(length: int = 24) -> str:
    alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*"
    return "".join(secrets.choice(alphabet) for _ in range(length))


def main():
    print("# RemitFlow Generated Secrets")
    print("# Generated by: python3 scripts/generate_secrets.py")
    print("# IMPORTANT: Store these in a secrets manager (HashiCorp Vault, AWS Secrets Manager)")
    print("# NEVER commit this file to version control")
    print()

    print("# ── Database ─────────────────────────────────────────────────────")
    print(f"POSTGRES_USER=remittance_admin")
    print(f"POSTGRES_PASSWORD={generate_password(32)}")
    print(f"POSTGRES_DB=remittance_prod")
    print()

    print("# ── Redis ────────────────────────────────────────────────────────")
    print(f"REDIS_PASSWORD={generate_password(32)}")
    print()

    print("# ── JWT & Encryption ─────────────────────────────────────────────")
    print(f"JWT_SECRET_KEY={generate_hex(64)}")
    print(f"ENCRYPTION_KEY={generate_fernet_key()}")
    print()

    print("# ── Application ──────────────────────────────────────────────────")
    print("ENVIRONMENT=production")
    print("DEBUG=false")
    print("LOG_LEVEL=WARNING")
    print("CORS_ORIGINS=https://app.remitflow.com,https://admin.remitflow.com")
    print()

    print("# ── HashiCorp Vault ──────────────────────────────────────────────")
    print("VAULT_ENABLED=true")
    print("VAULT_ADDR=https://vault.internal.remitflow.com:8200")
    print(f"VAULT_TOKEN={generate_urlsafe(32)}  # Replace with actual Vault token")
    print()

    print("# ── Monitoring ───────────────────────────────────────────────────")
    print("SENTRY_DSN=https://YOUR_SENTRY_KEY@sentry.io/YOUR_PROJECT_ID")
    print(f"GRAFANA_ADMIN_PASSWORD={generate_password(24)}")
    print()

    print("# ── Third-Party API Keys (obtain from each provider) ─────────────")
    print("WISE_API_KEY=REPLACE_WITH_WISE_API_KEY")
    print("REMITLY_API_KEY=REPLACE_WITH_REMITLY_API_KEY")
    print("STRIPE_API_KEY=sk_live_REPLACE_WITH_STRIPE_KEY")
    print("PAYSTACK_SECRET_KEY=sk_live_REPLACE_WITH_PAYSTACK_KEY")
    print("FLUTTERWAVE_SECRET_KEY=FLWSECK_REPLACE_WITH_FLUTTERWAVE_KEY")
    print("TWILIO_ACCOUNT_SID=REPLACE_WITH_TWILIO_SID")
    print("TWILIO_AUTH_TOKEN=REPLACE_WITH_TWILIO_TOKEN")
    print("SENDGRID_API_KEY=SG.REPLACE_WITH_SENDGRID_KEY")
    print("FIREBASE_SERVER_KEY=REPLACE_WITH_FIREBASE_SERVER_KEY")
    print("CIRCLE_API_KEY=REPLACE_WITH_CIRCLE_API_KEY")
    print("INFURA_PROJECT_ID=REPLACE_WITH_INFURA_PROJECT_ID")
    print("ALCHEMY_API_KEY=REPLACE_WITH_ALCHEMY_KEY")
    print("AFRICAS_TALKING_API_KEY=REPLACE_WITH_AT_KEY")
    print("AFRICAS_TALKING_USERNAME=REPLACE_WITH_AT_USERNAME")
    print("INTERSWITCH_CLIENT_ID=REPLACE_WITH_INTERSWITCH_CLIENT_ID")
    print("NIBSS_API_KEY=REPLACE_WITH_NIBSS_KEY")
    print()

    print("# ── Blockchain (use Vault Transit in production) ──────────────────")
    print("# BLOCKCHAIN_PRIVATE_KEY must NOT be set in production env vars.")
    print("# Use Vault Transit engine: vault write transit/sign/blockchain-key ...")
    print()

    print("# ── Webhook Secrets ──────────────────────────────────────────────")
    print(f"PAYSTACK_WEBHOOK_SECRET={generate_hex(32)}")
    print(f"FLUTTERWAVE_WEBHOOK_SECRET={generate_hex(32)}")
    print(f"STRIPE_WEBHOOK_SECRET=whsec_{generate_hex(32)}")
    print(f"WISE_WEBHOOK_SECRET={generate_hex(32)}")
    print()

    print("# ── Idempotency ──────────────────────────────────────────────────")
    print("IDEMPOTENCY_KEY_TTL_SECONDS=86400")
    print()

    print("# ── Backup ───────────────────────────────────────────────────────")
    print("BACKUP_S3_BUCKET=remitflow-prod-backups")
    print("BACKUP_S3_REGION=us-east-1")
    print("AWS_ACCESS_KEY_ID=REPLACE_WITH_AWS_KEY")
    print("AWS_SECRET_ACCESS_KEY=REPLACE_WITH_AWS_SECRET")
    print()


if __name__ == "__main__":
    main()
