import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/mockito.dart';
import 'package:mockito/annotations.dart';
import 'state_manager.dart'; // Assuming state_manager.dart is in the same directory

// Generate a Mock class for ApiService
@GenerateMocks([ApiService])
import 'state_manager_test.mocks.dart';

void main() {
  // MockApiService is defined in state_manager.dart, but we will use the MockApiService
  // generated by mockito for better control over method calls and verification.
  late MockApiService mockApiService;
  late StateManager stateManager;

  // Setup function to run before each test
  setUp(() {
    // Initialize the mock and the StateManager before every test
    mockApiService = MockApiService();
    stateManager = StateManager(mockApiService);
  });

  // Group of tests for the initial state
  group('StateManager - Initial State', () {
    test('should have correct initial values', () {
      expect(stateManager.data, 'Initial Data');
      expect(stateManager.isLoading, false);
      expect(stateManager.error, isNull);
    });
  });

  // Group of tests for API data loading
  group('StateManager - loadData (API interaction)', () {
    const String testId = 'user-123';
    const String successData = 'Data for $testId';

    test('should handle successful data loading and notify listeners', () {
      // 1. Arrange: Mock the successful API call
      when(mockApiService.fetchData(testId))
          .thenAnswer((_) async => successData);

      // 2. Act & Assert: Verify state transitions and notifications
      // Use expectLater to check for notifications
      expect(stateManager.data, 'Initial Data', reason: 'Pre-condition check');

      // Use a list to capture the sequence of notifications
      final List<String> notifications = [];
      stateManager.addListener(() {
        // Capture the state at the moment of notification
        notifications.add(
            'isLoading: ${stateManager.isLoading}, data: ${stateManager.data}, error: ${stateManager.error}');
      });

      // Act
      final future = stateManager.loadData(testId);

      // 1st notification (start loading): isLoading=true
      expect(stateManager.isLoading, true);
      expect(stateManager.data, 'Initial Data');
      expect(stateManager.error, isNull);

      // Wait for the async operation to complete
      return future.then((_) {
        // 2nd notification (loading complete): isLoading=false, data updated
        expect(stateManager.isLoading, false);
        expect(stateManager.data, successData);
        expect(stateManager.error, isNull);

        // Verify the sequence of notifications
        expect(notifications.length, 2,
            reason: 'Should notify listeners exactly twice (start and end)');
        expect(notifications[0],
            'isLoading: true, data: Initial Data, error: null');
        expect(notifications[1],
            'isLoading: false, data: $successData, error: null');

        // Verify that the mock method was called exactly once
        verify(mockApiService.fetchData(testId)).called(1);
      });
    });

    test('should handle API error and notify listeners', () {
      // 1. Arrange: Mock the failed API call
      final Exception error = Exception('Failed to fetch data');
      when(mockApiService.fetchData(testId)).thenThrow(error);

      // 2. Act & Assert: Verify state transitions and notifications
      final List<String> notifications = [];
      stateManager.addListener(() {
        notifications.add(
            'isLoading: ${stateManager.isLoading}, data: ${stateManager.data}, error: ${stateManager.error}');
      });

      // Act
      final future = stateManager.loadData(testId);

      // 1st notification (start loading): isLoading=true
      expect(stateManager.isLoading, true);

      // Wait for the async operation to complete
      return future.then((_) {
        // 2nd notification (loading complete with error): isLoading=false, error updated
        expect(stateManager.isLoading, false);
        expect(stateManager.data, 'Error occurred',
            reason: 'Data should be updated to "Error occurred" on failure');
        expect(stateManager.error, error.toString());

        // Verify the sequence of notifications
        expect(notifications.length, 2,
            reason: 'Should notify listeners exactly twice (start and end)');
        expect(notifications[0],
            'isLoading: true, data: Initial Data, error: null');
        expect(notifications[1],
            'isLoading: false, data: Error occurred, error: ${error.toString()}');

        // Verify that the mock method was called exactly once
        verify(mockApiService.fetchData(testId)).called(1);
      });
    });
  });

  // Group of tests for local state updates
  group('StateManager - updateLocalData (Local state)', () {
    test('should update local data successfully and notify listeners', () {
      const String newData = 'New Local Data';

      // Use a mock listener to verify notification
      final listener = MockListener();
      stateManager.addListener(listener);

      // Act
      stateManager.updateLocalData(newData);

      // Assert
      expect(stateManager.data, newData);
      expect(stateManager.error, isNull);
      expect(stateManager.isLoading, false);

      // Verify that notifyListeners was called
      verify(listener()).called(1);
    });

    test('should throw ArgumentError for empty data (Edge Case)', () {
      // Assert that calling the method with an empty string throws an ArgumentError
      expect(() => stateManager.updateLocalData(''), throwsA(isA<ArgumentError>()));

      // Verify that state was not changed
      expect(stateManager.data, 'Initial Data');
      // Verify that notifyListeners was NOT called (since the method threw before it)
      // We can't directly verify notifyListeners was not called without a more complex mock,
      // but we can infer it from the exception being thrown.
    });
  });

  // Group of tests for other methods
  group('StateManager - Other Methods', () {
    test('resetState should restore initial values and notify listeners', () async {
      // 1. Arrange: Change the state first
      // Mock a successful API call to change the state
      when(mockApiService.fetchData('test')).thenAnswer((_) async => 'Some Data');
      await stateManager.loadData('test');
      expect(stateManager.data, 'Some Data');

      // Use a mock listener to verify notification
      final listener = MockListener();
      stateManager.addListener(listener);

      // Act
      stateManager.resetState();

      // Assert
      expect(stateManager.data, 'Initial Data');
      expect(stateManager.isLoading, false);
      expect(stateManager.error, isNull);

      // Verify that notifyListeners was called
      verify(listener()).called(1);
    });
  });
}

// A simple mock class to verify that notifyListeners is called
class MockListener extends Mock {
  void call();
}