"""
UPI Payment Gateway Service
"""

from .client import UPIClient
from typing import Dict
import os

_PLACEHOLDER_VALUES = {"test_key", "changeme", "change_me", "placeholder", "your_api_key_here"}


def _require_env(name: str) -> str:
    """Read a required credential from the environment.

    Fails fast at startup if the variable is unset, empty, or still a
    known placeholder value -- never fall back to a fake credential on a
    money path.
    """
    value = os.getenv(name)
    if not value or value.strip().lower() in _PLACEHOLDER_VALUES:
        raise RuntimeError(
            f"Missing required configuration: {name} is unset or a placeholder. "
            "Refusing to start the upi gateway without real credentials."
        )
    return value


class UpiService:
    def __init__(self):
        self.client = UPIClient(
            merchant_id=_require_env("UPI_MERCHANT_ID"),
            merchant_key=_require_env("UPI_MERCHANT_KEY"),
            vpa=_require_env("UPI_VPA"),
            base_url=os.getenv("UPI_BASE_URL", "https://api.upi.npci.org.in"),
        )

    async def process_transfer(self, transfer_data: Dict) -> Dict:
        """Initiate a UPI collect request.

        transfer_data keys: payer_vpa, amount, note (optional),
        reference_id (optional — generated by caller for idempotency).
        """
        try:
            result = await self.client.collect_request(
                payer_vpa=transfer_data["payer_vpa"],
                amount=transfer_data["amount"],
                note=transfer_data.get("note", "Remittance"),
                reference_id=transfer_data["reference_id"],
            )
            return {
                "success": True,
                "gateway": "upi",
                "transfer_id": result.get("txn_id"),
                "status": result.get("status"),
                "data": result
            }
        except Exception as e:
            return {
                "success": False,
                "gateway": "upi",
                "error": str(e)
            }

    async def check_status(self, transfer_id: str) -> Dict:
        """Check transaction status by reference_id"""
        try:
            result = await self.client.check_status(reference_id=transfer_id)
            return {
                "success": True,
                "gateway": "upi",
                "status": result.get("status"),
                "data": result
            }
        except Exception as e:
            return {
                "success": False,
                "gateway": "upi",
                "error": str(e)
            }
