apiVersion: apps/v1
kind: Deployment
metadata:
  name: permify
  namespace: permify
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: permify
        env:
        - name: PERMIFY_AUTOCMIGRATE
          value: "true"
        - name: PERMIFY_DATABASE_ENGINE
          value: "postgres"
        - name: PERMIFY_DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: permify-db-secret
              key: uri
