{{- if and .Values.backend.fastapi.enabled .Values.backend.fastapi.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "remittance-platform.fullname" . }}-fastapi
  labels:
    {{- include "remittance-platform.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "remittance-platform.fullname" . }}-fastapi
  minReplicas: {{ .Values.backend.fastapi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.backend.fastapi.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.backend.fastapi.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
