apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: postgres-metadata-service-scaler
  namespace: pix-integration
spec:
  scaleTargetRef:
    name: postgres-metadata-service
  minReplicaCount: 2
  maxReplicaCount: 10
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "70"
  - type: memory
    metadata:
      type: Utilization
      value: "80"
