from datetime import datetime
from typing import Optional, Any, List
from decimal import Decimal
from pydantic import BaseModel, Field, validator
from models import TransactionStatus, RefundStatus

# --- Base Schemas ---

class TransactionBase(BaseModel):
    order_id: str = Field(..., description="Unique ID generated by the merchant/system.")
    amount: Decimal = Field(..., gt=0, decimal_places=2, description="Transaction amount.")
    vpa: str = Field(..., description="Virtual Payment Address (UPI ID) of the payer.")
    user_id: Optional[int] = Field(None, description="ID of the user initiating the transaction.")

    class Config:
        orm_mode = True
        use_enum_values = True

class RefundBase(BaseModel):
    transaction_id: int = Field(..., description="ID of the transaction to be refunded.")
    amount: Decimal = Field(..., gt=0, decimal_places=2, description="Refund amount.")

    class Config:
        orm_mode = True
        use_enum_values = True

class WebhookEventBase(BaseModel):
    event_id: str = Field(..., description="Unique ID for the event from the PG.")
    event_type: str = Field(..., description="Type of event (e.g., 'payment.captured').")
    payload: Any = Field(..., description="Full payload of the webhook event.")

    class Config:
        orm_mode = True
        use_enum_values = True

# --- Request Schemas (Input) ---

class TransactionCreate(TransactionBase):
    pass

class TransactionUpdate(BaseModel):
    status: TransactionStatus = Field(..., description="New status of the transaction.")
    transaction_id: Optional[str] = Field(None, description="Unique ID from the Payment Gateway (PG).")
    gateway_response: Optional[Any] = Field(None, description="Raw response from the Payment Gateway.")

    class Config:
        use_enum_values = True

class RefundCreate(RefundBase):
    pass

class WebhookEventCreate(WebhookEventBase):
    pass

# --- Response Schemas (Output) ---

class TransactionResponse(TransactionBase):
    id: int
    transaction_id: Optional[str]
    currency: str
    status: TransactionStatus
    gateway_response: Optional[Any]
    created_at: datetime
    updated_at: datetime

    class Config:
        json_encoders = {
            Decimal: lambda v: str(v)
        }

class RefundResponse(RefundBase):
    id: int
    refund_id: str
    status: RefundStatus
    gateway_response: Optional[Any]
    created_at: datetime
    updated_at: datetime

    class Config:
        json_encoders = {
            Decimal: lambda v: str(v)
        }

class WebhookEventResponse(WebhookEventBase):
    id: int
    processed: bool
    created_at: datetime
    updated_at: datetime

# --- List Schemas ---

class TransactionListResponse(BaseModel):
    total: int
    transactions: List[TransactionResponse]

class RefundListResponse(BaseModel):
    total: int
    refunds: List[RefundResponse]

# --- Utility Schemas ---

class HealthCheck(BaseModel):
    status: str = "ok"
    service: str = "upi-integration-service"
    timestamp: datetime