apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "caddy.fullname" . }}-config
  labels:
    {{- include "caddy.labels" . | nindent 4 }}
data:
  Caddyfile: |
    {{ .Files.Get "files/Caddyfile" | nindent 4 }}
