apiVersion: v1
kind: Service
metadata:
  name: {{ include "caddy.fullname" . }}
  labels:
    {{- include "caddy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.https }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.service.ports.https }}
      targetPort: https-udp
      protocol: UDP
      name: https-udp
    - port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "caddy.selectorLabels" . | nindent 4 }}
