#!/usr/bin/env python3
"""
Generates a SQL migration file for missing indexes on userId columns.
"""
import re

with open('drizzle/schema.ts') as f:
    content = f.read()

tables = re.findall(r'export const (\w+) = pgTable\(\"(\w+)\"', content)

# Check for tables with userId but no index
missing_indexes = []
for table_var, table_name in tables:
    pattern = rf'export const {re.escape(table_var)} = pgTable\(.*?(?=\nexport const|\Z)'
    match = re.search(pattern, content, re.DOTALL)
    if match:
        block = match.group(0)
        if 'userId' in block and 'index' not in block and 'uniqueIndex' not in block:
            missing_indexes.append((table_var, table_name))

print(f"Tables needing userId index: {len(missing_indexes)}")

# Generate SQL
sql_lines = [
    "-- RemitFlow: Missing userId index migration",
    "-- Auto-generated by scripts/generate-missing-indexes.py",
    ""
]
for table_var, table_name in missing_indexes:
    idx_name = f"idx_{table_name}_user_id"
    sql_lines.append(f'CREATE INDEX IF NOT EXISTS "{idx_name}" ON "{table_name}" ("userId");')

with open('drizzle/0052_missing_user_indexes.sql', 'w') as f:
    f.write('\n'.join(sql_lines) + '\n')

print(f"Written to drizzle/0052_missing_user_indexes.sql")
