apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tigerbeetle-ha
  namespace: tigerbeetle
spec:
  replicas: 3
  serviceName: tigerbeetle
  podManagementPolicy: Parallel
  template:
    spec:
      containers:
      - name: tigerbeetle
        env:
        - name: TIGERBEETLE_REPLICA_ADDRESSES
          value: "tigerbeetle-0.tigerbeetle,tigerbeetle-1.tigerbeetle,tigerbeetle-2.tigerbeetle"
