apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: 54remit-backend-cert
  namespace: 54remit
spec:
  secretName: 54remit-backend-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: 54remit.upi.dev
  dnsNames:
    - "54remit.upi.dev"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: 54remit-verification-ui-cert
  namespace: 54remit
spec:
  secretName: 54remit-verification-ui-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kyc.54remit.upi.dev
  dnsNames:
    - "kyc.54remit.upi.dev"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: 54remit-client-web-app-cert
  namespace: 54remit
spec:
  secretName: 54remit-client-web-app-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: app.54remit.upi.dev
  dnsNames:
    - "app.54remit.upi.dev"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: 54remit-tenant-web-app-cert
  namespace: 54remit
spec:
  secretName: 54remit-tenant-web-app-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: tenant.54remit.upi.dev
  dnsNames:
    - "tenant.54remit.upi.dev"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: 54remit-admin-web-app-cert
  namespace: 54remit
spec:
  secretName: 54remit-admin-web-app-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: admin.54remit.upi.dev
  dnsNames:
    - "admin.54remit.upi.dev"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: 54remit-compliance-ui-cert
  namespace: 54remit
spec:
  secretName: 54remit-compliance-ui-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: compliance.54remit.upi.dev
  dnsNames:
    - "compliance.54remit.upi.dev"
