apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: 54remit-backend-tls
  namespace: 54remit
spec:
  ingressClassName: appsec-apisix-prod
  hosts:
    - 54remit.upi.dev
  secret:
    name: 54remit-backend-cert
    namespace: 54remit
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: 54remit-verification-ui-tls
  namespace: 54remit
spec:
  ingressClassName: appsec-apisix-prod
  hosts:
    - kyc.54remit.upi.dev
  secret:
    name: 54remit-verification-ui-cert
    namespace: 54remit
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: 54remit-client-web-app-tls
  namespace: 54remit
spec:
  ingressClassName: appsec-apisix-prod
  hosts:
    - app.54remit.upi.dev
  secret:
    name: 54remit-client-web-app-cert
    namespace: 54remit
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: 54remit-tenant-web-app-tls
  namespace: 54remit
spec:
  ingressClassName: appsec-apisix-prod
  hosts:
    - tenant.54remit.upi.dev
  secret:
    name: 54remit-tenant-web-app-cert
    namespace: 54remit
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: 54remit-admin-web-app-tls
  namespace: 54remit
spec:
  ingressClassName: appsec-apisix-prod
  hosts:
    - admin.54remit.upi.dev
  secret:
    name: 54remit-admin-web-app-cert
    namespace: 54remit
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: 54remit-compliance-ui-tls
  namespace: 54remit
spec:
  ingressClassName: appsec-apisix-prod
  hosts:
    - compliance.54remit.upi.dev
  secret:
    name: 54remit-compliance-ui-cert
    namespace: 54remit
