package com.example.app.data.service

import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.withContext
import java.io.IOException
import java.util.UUID

// --- 1. Data Models and Enums ---

/**
 * Represents the status of a Know Your Customer (KYC) check.
 * This status is crucial for compliance before any transaction can proceed.
 */
enum class KycStatus {
    /** KYC process is currently under review. */
    PENDING,
    /** KYC has been successfully verified and approved. */
    APPROVED,
    /** KYC failed verification and the user is blocked from transactions. */
    REJECTED,
    /** KYC information is missing and must be provided. */
    REQUIRED
}

/**
 * Represents the data required to initiate a transaction.
 * All fields are mandatory for a valid transaction request.
 * @property amount The transaction amount, must be a positive value.
 * @property currency The three-letter ISO 4217 currency code (e.g., "USD", "EUR").
 * @property recipientId The unique identifier of the recipient account or user.
 * @property transactionType The category of the transaction (e.g., "TRANSFER", "PAYMENT", "WITHDRAWAL").
 * @property description An optional, brief description for the transaction.
 */
data class TransactionRequest(
    val amount: Double,
    val currency: String,
    val recipientId: String,
    val transactionType: String,
    val description: String? = null
)

/**
 * Represents the final result of a transaction attempt returned by the backend.
 * @property transactionId The unique ID of the initiated transaction, generated by the server.
 * @property status The final or intermediate status of the transaction (e.g., "PROCESSING", "COMPLETED", "FAILED").
 * @property message A human-readable message providing context on the transaction status.
 * @property timestamp The time the transaction was recorded on the server.
 */
data class TransactionResponse(
    val transactionId: String,
    val status: String,
    val message: String,
    val timestamp: Long = System.currentTimeMillis()
)

// --- 2. Custom Exceptions ---

/**
 * Base class for all custom exceptions in the transaction flow.
 */
sealed class TransactionException(message: String, cause: Throwable? = null) : Exception(message, cause)

/**
 * Thrown when a business rule is violated (e.g., insufficient funds, daily limit exceeded).
 * This is typically a 4xx error from the API that is not a network or server issue.
 */
class BusinessRuleException(message: String) : TransactionException(message)

/**
 * Thrown when the user's KYC status prevents the transaction from proceeding.
 */
class KycRequiredException(val kycStatus: KycStatus, message: String) : TransactionException(message)

/**
 * Thrown for general API errors that are not specific business rules (e.g., 5xx server errors).
 */
class ApiErrorException(message: String, cause: Throwable? = null) : TransactionException(message, cause)

/**
 * Thrown for network-related issues (e.g., no internet connection, timeout).
 */
class NetworkException(message: String, cause: Throwable? = null) : TransactionException(message, cause)

// --- 3. Standardized Result Wrappers ---

/**
 * A standardized result wrapper for the API layer, distinguishing between success and failure.
 */
sealed class ApiResult<out T : Any> {
    data class Success<out T : Any>(val data: T) : ApiResult<T>()
    data class Failure(val exception: TransactionException) : ApiResult<Nothing>()
}

/**
 * A standardized result wrapper for the Service layer, used to communicate status updates
 * and final results back to the UI via Kotlin Flow.
 */
sealed class ServiceResult<out T : Any> {
    /** Represents a successful operation or an intermediate status update. */
    data class Success<out T : Any>(val data: T) : ServiceResult<T>()
    /** Represents a final error that terminated the transaction flow. */
    data class Error(val exception: TransactionException, val userMessage: String) : ServiceResult<Nothing>()
    /** Represents an ongoing status update during the transaction process. */
    data class StatusUpdate(val status: String, val message: String) : ServiceResult<Nothing>()
}

// --- 4. API Interface and Mock Implementation ---

/**
 * Defines the contract for all backend interactions related to transactions and KYC.
 * In a production environment, this would be implemented by a library like Retrofit.
 */
interface TransactionApi {
    /**
     * Suspended function to asynchronously fetch the current KYC status.
     * @return An [ApiResult] containing the [KycStatus] on success, or a [TransactionException] on failure.
     */
    suspend fun getKycStatus(): ApiResult<KycStatus>

    /**
     * Suspended function to submit a transaction request to the server.
     * @param request The [TransactionRequest] data.
     * @return An [ApiResult] containing the [TransactionResponse] on success, or a [TransactionException] on failure.
     */
    suspend fun submitTransaction(request: TransactionRequest): ApiResult<TransactionResponse>
}

/**
 * Mock implementation of the [TransactionApi] for development and testing purposes.
 * Simulates network latency and various success/failure scenarios.
 */
class MockTransactionApi : TransactionApi {
    private val kycSimulationStatus = KycStatus.APPROVED // Change to PENDING, REJECTED, or REQUIRED for testing

    override suspend fun getKycStatus(): ApiResult<KycStatus> {
        delay(500) // Simulate network latency
        return try {
            when (kycSimulationStatus) {
                KycStatus.APPROVED -> ApiResult.Success(KycStatus.APPROVED)
                KycStatus.PENDING -> ApiResult.Success(KycStatus.PENDING)
                KycStatus.REJECTED -> ApiResult.Success(KycStatus.REJECTED)
                KycStatus.REQUIRED -> ApiResult.Success(KycStatus.REQUIRED)
            }
        } catch (e: IOException) {
            ApiResult.Failure(NetworkException("Failed to connect to KYC service.", e))
        } catch (e: Exception) {
            ApiResult.Failure(ApiErrorException("Unknown error during KYC check.", e))
        }
    }

    override suspend fun submitTransaction(request: TransactionRequest): ApiResult<TransactionResponse> {
        delay(1000) // Simulate network latency
        return try {
            when {
                request.amount > 5000.0 -> {
                    // Simulate a business rule violation (e.g., daily limit)
                    ApiResult.Failure(BusinessRuleException("Transaction amount exceeds the maximum limit of 5000.0 ${request.currency}."))
                }
                request.amount < 1.0 -> {
                    // Simulate another business rule violation (e.g., minimum amount)
                    ApiResult.Failure(BusinessRuleException("Transaction amount is below the minimum required amount of 1.0 ${request.currency}."))
                }
                else -> {
                    // Simulate a successful transaction submission
                    ApiResult.Success(
                        TransactionResponse(
                            transactionId = "TXN-${UUID.randomUUID()}",
                            status = "PROCESSING",
                            message = "Transaction submitted successfully. Awaiting final confirmation from the ledger."
                        )
                    )
                }
            }
        } catch (e: IOException) {
            ApiResult.Failure(NetworkException("Transaction submission failed due to network error.", e))
        } catch (e: Exception) {
            ApiResult.Failure(ApiErrorException("Unknown error during transaction submission.", e))
        }
    }
}

// --- 5. Service Manager ---

/**
 * The core service manager responsible for orchestrating the entire transaction flow.
 * It handles input validation, KYC pre-checks, API communication, and error mapping.
 *
 * It utilizes Kotlin Coroutines and Flow to provide a modern, reactive, and
 * non-blocking interface for the Android application's ViewModel/Presenter layer.
 *
 * @property api The [TransactionApi] implementation for backend communication.
 * @property defaultDispatcher The [CoroutineDispatcher] to use for all background, blocking operations (e.g., Dispatchers.IO).
 */
class TransactionFlowManager(
    private val api: TransactionApi = MockTransactionApi(),
    private val defaultDispatcher: CoroutineDispatcher = Dispatchers.IO
) {

    /**
     * Orchestrates the transaction process, including automatic KYC checking and submission.
     *
     * The process emits a stream of [ServiceResult] updates to the collector:
     * 1. **Validation**: Checks for valid input parameters.
     * 2. **KYC Check**: Calls the API to verify the user's compliance status.
     * 3. **Submission**: If KYC is approved, the transaction is submitted.
     * 4. **Final Result**: Emits the final success or error state.
     *
     * @param request The [TransactionRequest] containing all necessary transaction details.
     * @return A [Flow] of [ServiceResult] providing real-time status updates and the final result.
     */
    fun initiateTransaction(request: TransactionRequest): Flow<ServiceResult<TransactionResponse>> = flow {
        // All heavy/suspending operations are executed within withContext(defaultDispatcher)
        withContext(defaultDispatcher) {
            // 1. Input Validation
            val validationError = validateRequest(request)
            if (validationError != null) {
                emit(validationError)
                return@withContext
            }

            // 2. KYC Status Check
            emit(ServiceResult.StatusUpdate("KYC_CHECKING", "Verifying user's compliance status..."))
            val kycStatusResult = api.getKycStatus()

            when (kycStatusResult) {
                is ApiResult.Success -> {
                    val kycStatus = kycStatusResult.data
                    if (kycStatus != KycStatus.APPROVED) {
                        handleKycFailure(kycStatus)
                        return@withContext
                    }
                }
                is ApiResult.Failure -> {
                    // Handle API layer failure during KYC check
                    emit(ServiceResult.Error(kycStatusResult.exception, "Failed to perform KYC check. Please try again."))
                    return@withContext
                }
            }

            // 3. Transaction Submission
            emit(ServiceResult.StatusUpdate("SUBMITTING", "KYC approved. Submitting transaction to the backend..."))
            val submissionResult = api.submitTransaction(request)

            when (submissionResult) {
                is ApiResult.Success -> {
                    // 4. Final Success
                    emit(ServiceResult.Success(submissionResult.data))
                }
                is ApiResult.Failure -> {
                    // Handle API layer failure during submission
                    val exception = submissionResult.exception
                    val userMessage = when (exception) {
                        is BusinessRuleException -> "Transaction failed: ${exception.message}"
                        is NetworkException -> "Connection error: Could not submit transaction. Check your internet."
                        else -> "An unexpected error occurred during submission."
                    }
                    emit(ServiceResult.Error(exception, userMessage))
                }
            }
        }
    }

    /**
     * Performs client-side validation of the [TransactionRequest].
     * @param request The request to validate.
     * @return A [ServiceResult.Error] if validation fails, or null if successful.
     */
    private fun validateRequest(request: TransactionRequest): ServiceResult.Error? {
        return when {
            request.amount <= 0.0 -> ServiceResult.Error(
                IllegalArgumentException("Amount must be positive."),
                "Invalid amount specified. Please enter a value greater than zero."
            )
            request.recipientId.isBlank() -> ServiceResult.Error(
                IllegalArgumentException("Recipient ID is missing."),
                "Recipient is required. Please select a valid recipient."
            )
            request.currency.length != 3 -> ServiceResult.Error(
                IllegalArgumentException("Invalid currency code."),
                "The currency code is invalid. Please use a 3-letter ISO code."
            )
            else -> null
        }
    }

    /**
     * Handles the scenario where the KYC status is not [KycStatus.APPROVED].
     * Emits a [ServiceResult.Error] with a specific [KycRequiredException].
     * @param kycStatus The non-approved KYC status.
     */
    private suspend fun handleKycFailure(kycStatus: KycStatus) {
        val message = when (kycStatus) {
            KycStatus.PENDING -> "KYC check is still pending. Please wait for approval."
            KycStatus.REJECTED -> "KYC check was rejected. You are blocked from initiating transactions."
            KycStatus.REQUIRED -> "KYC is required. Please complete your profile verification."
            KycStatus.APPROVED -> "KYC Approved (Should not happen here)" // Should not happen
        }
        emit(
            ServiceResult.Error(
                KycRequiredException(kycStatus, "Transaction blocked due to KYC status: $kycStatus"),
                message
            )
        )
    }

    /**
     * A utility function to demonstrate how the service can be used.
     * This is not part of the core service but useful for testing/example.
     */
    suspend fun runExample() {
        val exampleRequest = TransactionRequest(
            amount = 1500.0,
            currency = "EUR",
            recipientId = "user_456789",
            transactionType = "TRANSFER",
            description = "Monthly rent payment"
        )

        println("--- Starting Transaction Flow Example ---")
        initiateTransaction(exampleRequest).collect { result ->
            when (result) {
                is ServiceResult.Success -> {
                    val response = result.data
                    println("SUCCESS: Transaction ID: ${response.transactionId} | Status: ${response.status} | Message: ${response.message}")
                }
                is ServiceResult.Error -> {
                    println("ERROR: ${result.userMessage} | Details: ${result.exception.localizedMessage}")
                }
                is ServiceResult.StatusUpdate -> {
                    println("STATUS UPDATE: ${result.status} | Message: ${result.message}")
                }
            }
        }
        println("--- Transaction Flow Example Finished ---")
    }
}
