// Package model defines the Kafka event schema for liveness check results.
// Events are published by the Node.js tRPC server and the Temporal workflow
// to the "kyc.liveness.result" topic after every selfie submission.
package model

// LivenessResultEvent is the JSON payload published to Kafka topic
// "kyc.liveness.result" by the Node.js KYC extract procedure and the
// Temporal livenessCheckActivity.
type LivenessResultEvent struct {
	// EventID is a UUID generated by the publisher for idempotency.
	EventID string `json:"event_id"`
	// OccurredAt is a Unix millisecond timestamp (UTC).
	OccurredAt int64 `json:"occurred_at"`

	// UserID is the internal DB user ID.
	UserID int64 `json:"user_id"`
	// KycDocID is the kycDocuments.id FK (may be 0 if not yet persisted).
	KycDocID int64 `json:"kyc_doc_id,omitempty"`
	// CorridorCode is the ISO-3166 sender country code (e.g. "NG", "GH").
	CorridorCode string `json:"corridor_code,omitempty"`

	// Passive liveness layer
	PassiveScore   *float64 `json:"passive_score,omitempty"`
	PassivePassed  *bool    `json:"passive_passed,omitempty"`
	SpoofingType   string   `json:"spoofing_type,omitempty"`

	// Active liveness layer
	ActiveBlinkCount      *int     `json:"active_blink_count,omitempty"`
	ActiveHeadMovementDeg *float64 `json:"active_head_movement_deg,omitempty"`
	ActivePassed          *bool    `json:"active_passed,omitempty"`

	// Deepfake detection layer
	DeepfakeScore   *float64 `json:"deepfake_score,omitempty"`
	DeepfakeMethod  string   `json:"deepfake_method,omitempty"`
	DeepfakePassed  *bool    `json:"deepfake_passed,omitempty"`

	// Overall result
	OverallLive bool   `json:"overall_live"`
	Source      string `json:"source"` // "trpc_extract" | "temporal_workflow"
}
