apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: redis123
  - name: enableTLS
    value: false
  - name: failover
    value: true
  - name: sentinelMasterName
    value: ""
  - name: redeliverInterval
    value: "30s"
  - name: processingTimeout
    value: "15s"
  - name: redisType
    value: "node"
  - name: redisDB
    value: "0"
  - name: redisMaxRetries
    value: "3"
  - name: redisMinRetryInterval
    value: "8ms"
  - name: redisMaxRetryInterval
    value: "512ms"
  - name: dialTimeout
    value: "5s"
  - name: readTimeout
    value: "3s"
  - name: writeTimeout
    value: "3s"
  - name: poolSize
    value: "20"
  - name: poolTimeout
    value: "5s"
  - name: maxConnAge
    value: "30m"
  - name: minIdleConns
    value: "2"
  - name: idleCheckFrequency
    value: "1m"
  - name: idleTimeout
    value: "5m"
auth:
  secretStore: kubernetes

