from datetime import datetime
from typing import Optional, List

from sqlalchemy import Column, Integer, String, DateTime, Text, Index
from sqlalchemy.ext.declarative import declarative_base
from pydantic import BaseModel, Field

# SQLAlchemy Base
Base = declarative_base()

class AuditLog(Base):
    """
    SQLAlchemy model for an Audit Log entry.
    """
    __tablename__ = "audit_logs"

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    service_name = Column(String(100), nullable=False, index=True, doc="The name of the service that generated the log.")
    user_id = Column(String(100), nullable=True, index=True, doc="The ID of the user who initiated the action (if applicable).")
    action = Column(String(100), nullable=False, index=True, doc="The type of action performed (e.g., USER_LOGIN, RESOURCE_CREATE).")
    resource_type = Column(String(100), nullable=False, index=True, doc="The type of resource affected (e.g., User, Account).")
    resource_id = Column(String(100), nullable=False, index=True, doc="The ID of the resource affected.")
    status = Column(String(50), nullable=False, doc="The outcome of the action (e.g., SUCCESS, FAILURE).")
    details = Column(Text, nullable=True, doc="JSON string or detailed text of the event.")
    ip_address = Column(String(50), nullable=True, doc="IP address from which the action originated.")

    __table_args__ = (
        # Composite index for common compliance queries (e.g., all actions by a user in a time range)
        Index('ix_user_action_time', user_id, action, timestamp.desc()),
        # Index for searching by resource
        Index('ix_resource', resource_type, resource_id),
    )

    def __repr__(self):
        return f"<AuditLog(id={self.id}, action='{self.action}', user_id='{self.user_id}')>"

# Pydantic Schemas

class AuditLogBase(BaseModel):
    """Base schema for an audit log entry."""
    service_name: str = Field(..., example="user-service", description="The name of the service that generated the log.")
    user_id: Optional[str] = Field(None, example="u-12345", description="The ID of the user who initiated the action (if applicable).")
    action: str = Field(..., example="USER_LOGIN_SUCCESS", description="The type of action performed.")
    resource_type: str = Field(..., example="User", description="The type of resource affected.")
    resource_id: str = Field(..., example="u-12345", description="The ID of the resource affected.")
    status: str = Field(..., example="SUCCESS", description="The outcome of the action (e.g., SUCCESS, FAILURE).")
    details: Optional[str] = Field(None, example='{"old_value": "...", "new_value": "..."}', description="JSON string or detailed text of the event.")
    ip_address: Optional[str] = Field(None, example="192.168.1.1", description="IP address from which the action originated.")

class AuditLogCreate(AuditLogBase):
    """Schema for creating a new audit log entry."""
    # timestamp is generated by the database/service, so it's not required for creation

class AuditLogResponse(AuditLogBase):
    """Schema for returning an audit log entry."""
    id: int = Field(..., example=1)
    timestamp: datetime = Field(..., example=datetime.utcnow())

    class Config:
        orm_mode = True

class AuditLogSearch(BaseModel):
    """Schema for searching audit logs."""
    service_name: Optional[str] = None
    user_id: Optional[str] = None
    action: Optional[str] = None
    resource_type: Optional[str] = None
    resource_id: Optional[str] = None
    status: Optional[str] = None
    start_time: Optional[datetime] = None
    end_time: Optional[datetime] = None

class AuditLogExport(BaseModel):
    """Schema for requesting an audit log export."""
    search_criteria: AuditLogSearch = Field(..., description="The search criteria for the logs to be exported.")
    export_format: str = Field(..., example="csv", description="The desired export format (e.g., csv, json).")
    recipient_email: str = Field(..., example="user@example.com", description="Email address to send the export link to.")

class ComplianceReport(BaseModel):
    """Schema for requesting a compliance report."""
    report_type: str = Field(..., example="GDPR_ACCESS_LOG", description="The type of compliance report requested.")
    start_time: datetime
    end_time: datetime
    target_user_id: Optional[str] = Field(None, description="Specific user ID for user-centric reports.")
    
class ComplianceReportResponse(BaseModel):
    """Schema for the response of a compliance report request."""
    report_id: str = Field(..., example="report-12345")
    status: str = Field(..., example="PENDING")
    message: str = Field(..., example="Report generation started. You will be notified when complete.")
    
class ExportResponse(BaseModel):
    """Schema for the response of an export request."""
    export_id: str = Field(..., example="export-67890")
    status: str = Field(..., example="PENDING")
    message: str = Field(..., example="Export job started. A link will be sent to the recipient email.")
