apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
metadata:
  name: k8s-ha-cluster
controlPlaneEndpoint: "loadbalancer.remitflow.com:6443"
etcd:
  external:
    endpoints:
    - https://etcd0.remitflow.com:2379
    - https://etcd1.remitflow.com:2379
    - https://etcd2.remitflow.com:2379
    caFile: /etc/kubernetes/pki/etcd/ca.crt
    certFile: /etc/kubernetes/pki/apiserver-etcd-client.crt
    keyFile: /etc/kubernetes/pki/apiserver-etcd-client.key
