{{- if .Values.api.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "remittance-platform.fullname" . }}-api-pdb
  labels:
    {{- include "remittance-platform.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.api.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "remittance-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
---
{{- end }}
{{- if .Values.pwa.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "remittance-platform.fullname" . }}-pwa-pdb
  labels:
    {{- include "remittance-platform.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pwa.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "remittance-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: pwa
{{- end }}
