import enum
from datetime import datetime
from typing import List, Optional
from decimal import Decimal

from pydantic import BaseModel, Field, condecimal
from sqlalchemy import Column, Integer, String, DateTime, Enum, ForeignKey, Numeric, Index
from sqlalchemy.orm import relationship, Mapped
from sqlalchemy.ext.declarative import declarative_base

# Assuming Base is imported from config.py in a real application, 
# but for a standalone file, we define it here.
Base = declarative_base()

# --- Enums ---

class TransactionStatus(enum.Enum):
    """Possible statuses for a payment transaction."""
    PENDING = "PENDING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    REFUNDED = "REFUNDED"
    CAPTURED = "CAPTURED"
    AUTHORIZED = "AUTHORIZED"

class ActivityType(enum.Enum):
    """Types of activities logged for a transaction."""
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    STATUS_CHANGE = "STATUS_CHANGE"
    ERROR = "ERROR"
    GATEWAY_CALL = "GATEWAY_CALL"

# --- SQLAlchemy Models ---

class PaymentTransaction(Base):
    """
    Main model for a Global Payment Gateway transaction.
    """
    __tablename__ = "payment_transactions"

    id = Column(Integer, primary_key=True, index=True)
    
    # Core Transaction Details
    transaction_id = Column(String, unique=True, nullable=False, index=True, doc="Unique identifier for the transaction, generated by the service.")
    amount = Column(Numeric(10, 2), nullable=False, doc="Transaction amount.")
    currency = Column(String(3), nullable=False, doc="Transaction currency (e.g., 'USD', 'EUR').")
    status = Column(Enum(TransactionStatus), nullable=False, default=TransactionStatus.PENDING, index=True, doc="Current status of the transaction.")
    
    # Customer/Source Details
    customer_id = Column(String, nullable=False, index=True, doc="Identifier for the customer initiating the transaction.")
    payment_method_type = Column(String, nullable=False, doc="Type of payment method (e.g., 'card', 'paypal', 'bank_transfer').")
    
    # Gateway Details
    gateway_name = Column(String, nullable=False, doc="Name of the payment gateway used (e.g., 'Stripe', 'Adyen').")
    gateway_transaction_id = Column(String, nullable=True, index=True, doc="Transaction ID provided by the payment gateway.")
    gateway_response_code = Column(String, nullable=True, doc="Response code from the payment gateway.")
    
    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    # Relationships
    activity_logs: Mapped[List["PaymentActivityLog"]] = relationship("PaymentActivityLog", back_populates="transaction", cascade="all, delete-orphan")

    __table_args__ = (
        Index("ix_payment_transactions_customer_status", "customer_id", "status"),
    )

    def __repr__(self):
        return f"<PaymentTransaction(id={self.id}, transaction_id='{self.transaction_id}', status='{self.status.value}')>"

class PaymentActivityLog(Base):
    """
    Activity log for tracking state changes and events related to a transaction.
    """
    __tablename__ = "payment_activity_logs"

    id = Column(Integer, primary_key=True, index=True)
    
    # Foreign Key to PaymentTransaction
    transaction_id = Column(Integer, ForeignKey("payment_transactions.id"), nullable=False, index=True)
    
    activity_type = Column(Enum(ActivityType), nullable=False, doc="Type of activity logged.")
    description = Column(String, nullable=False, doc="Detailed description of the activity.")
    timestamp = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    
    # Optional context data (e.g., gateway raw response)
    context_data = Column(String, nullable=True, doc="JSON string of additional context data.")

    # Relationships
    transaction: Mapped["PaymentTransaction"] = relationship("PaymentTransaction", back_populates="activity_logs")

    def __repr__(self):
        return f"<PaymentActivityLog(id={self.id}, type='{self.activity_type.value}', transaction_id={self.transaction_id})>"

# --- Pydantic Schemas ---

# Base Schema for shared attributes
class PaymentTransactionBase(BaseModel):
    """Base schema for payment transaction data."""
    amount: condecimal(max_digits=10, decimal_places=2) = Field(..., description="Transaction amount.")
    currency: str = Field(..., min_length=3, max_length=3, description="Transaction currency (e.g., 'USD').")
    customer_id: str = Field(..., description="Identifier for the customer.")
    payment_method_type: str = Field(..., description="Type of payment method (e.g., 'card').")
    gateway_name: str = Field(..., description="Name of the payment gateway to use.")

# Schema for creating a new transaction
class PaymentTransactionCreate(PaymentTransactionBase):
    """Schema for creating a new payment transaction."""
    pass

# Schema for updating an existing transaction (partial update)
class PaymentTransactionUpdate(BaseModel):
    """Schema for updating an existing payment transaction."""
    status: Optional[TransactionStatus] = Field(None, description="New status of the transaction.")
    gateway_transaction_id: Optional[str] = Field(None, description="Transaction ID from the payment gateway.")
    gateway_response_code: Optional[str] = Field(None, description="Response code from the payment gateway.")
    
    class Config:
        use_enum_values = True

# Schema for a full response (includes database-generated fields)
class PaymentTransactionResponse(PaymentTransactionBase):
    """Schema for returning a payment transaction object."""
    id: int = Field(..., description="Database primary key.")
    transaction_id: str = Field(..., description="Service-generated unique transaction ID.")
    status: TransactionStatus = Field(..., description="Current status of the transaction.")
    gateway_transaction_id: Optional[str] = None
    gateway_response_code: Optional[str] = None
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True
        use_enum_values = True

# Schema for activity log response
class PaymentActivityLogResponse(BaseModel):
    """Schema for returning an activity log entry."""
    id: int
    transaction_id: int
    activity_type: ActivityType
    description: str
    timestamp: datetime
    context_data: Optional[str] = None

    class Config:
        from_attributes = True
        use_enum_values = True

# Schema for a transaction response that includes its activity logs
class PaymentTransactionDetailResponse(PaymentTransactionResponse):
    """Schema for returning a payment transaction with its activity logs."""
    activity_logs: List[PaymentActivityLogResponse] = []
    
    class Config:
        from_attributes = True
        use_enum_values = True
