apiVersion: osp-director.openstack.org/v1beta1
kind: OpenStackControlPlane
metadata:
  name: openstack-ha
  namespace: openstack
spec:
  passwordSecret: openstack-password-secret
  openStackRelease: "wallaby"
  controlPlane: 
    replicas: 3
  mysql:
    replicas: 3
  redis:
    replicas: 3
  rabbitmq:
    replicas: 3
